### ISSUE TITLE
Cupy Not working on CUDA 9.1

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [cupy/cupy#1057]
Hello,

I can't get cupy to work with cuda 9.1.

Here are the steps I took

- Install cuda 9.1 from Nvidia's website
- Create a fresh anaconda environment
- install cupy-cuda91
- `x = cupy.random.uniform(size=100)`
- And I get the same error as #1005. Sadly this is on a cluster and other people are running jobs on it I cannot just reinstall everything as if it was a virtual machine.

Here are more details:

```
leclerc@mapmaker-gpu ~> nvcc --version                                                                                                                                      (sandip) 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```
```
leclerc@mapmaker-gpu ~> pip freeze                                                                                                                                          (sandip) 
botocore==1.9.13
certifi==2018.1.18
colorama==0.3.7
cupy-cuda91==4.0.0rc1
fastrlock==0.3
jmespath==0.9.3
numpy==1.14.2
pyasn1==0.4.2
rsa==3.4.2
s3transfer==0.1.13
six==1.11.0
```

Thank you for your help

**Comment by GuillaumeLeclerc** [comment]
I downgraded cuda, installed cupy-cuda80 and the problem is gone. So I think there is a problem with cuda 9.1

**Comment by kmaehashi** [comment]
The problem is that you have CUDA 8.0 version of `libnvrtc-builtins.so` on your system.

* Please check `$D_LIBRARY_PATH` environment variable.
* Please run `ldconfig -p | grep -F libnvrtc-builtins.so` and make sure that the first one is `libnvrtc-builtins.so.9.0`.

I guess you will see `libnvrtc-builtins.so.8.0` in the second step. In that case, you need to find & remove the directory path from `/etc/ld.so.conf` and/or `/etc/ld.so.conf.d/*.conf` and run `ldconfig`.

**Comment by GuillaumeLeclerc** [comment]
You are right. Thanks.
