### ISSUE TITLE
implement cupy.linalg.lstsq

### ISSUE THREAD

**Issue by brandondube** [cupy/cupy#1273]
This function is missing from cupy's `linalg` module.  I am not sure if it is iterative, and therefore difficult/impossible to implement with CUDA.

**Comment by cjekel** [comment]
I'd be happy to contribute a ```cupy.linalg.lstsq```. I have on my desk a version which uses QR decomposition to solve a least squares problem. Perhaps I could also investigate a SVD version. 

Looking at [numpy.linalg.lstsq](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html), it doesn't make sense to include the optional parameter ```rcond``` since this isn't used in cupy.linalg.  Also, it doesn't make sense to return the residuals, rank, or s in the cupy implementation because these will all be extra calculations. So this would be a limited version of the numpy equivalent, that only returns the least squares solution. What are some thoughts on this?

```numpy.linalg.lstsq``` defaults to using [GELSD](http://www.netlib.org/lapack/lug/node27.html#tabdrivellsq) which is a divide-and-conquer SVD approach to solve a least squares problem. This is a numerically robust method. QR decomposition is slightly less expensive, but more susceptible to ill conditioning. See slide 42 of 43 in [these notes](http://www.cs.princeton.edu/courses/archive/fall11/cos323/notes/cos323_f11_lecture09_svd.pdf) where householder is a form of QR decomposition. 

Should the default behavior be to solve the least squares problem with SVD like numpy, with an optional method to solve using QR decomposition? Numpy doesn't have these choices, but I could imagine that users would be interested in the faster QR decomposition. 

---
 
I'd just like to quickly introduce myself to the cupy community. A couple weeks ago I stumbled upon cupy and I was very excited to see the numpy like Python syntax that makes this cupy very easy to use! I'm a PhD candidate at the University of Florida, and I've performed a number of least squares fits. I have a small Python library that currently uses either scipy.linalg.lstsq or tensorflow.linalg.lstsq to fit piecewise linear functions.
