### ISSUE TITLE
cupy garbage collection is 100-time slower than GPU computing

### ISSUE THREAD

**Issue by fiarabbit** [cupy/cupy#1294]
I found an interesting phenomenon about cupy.
If python's garbage collection is on, the computation elapsed time is 100 longer than when it is off.

This may be a known issue, but it is just enough to surprise me that `[a: cp.ndarray * 3.0 for i in range(2)]` is 100-time slower than `[a: cp.ndarray * 3.0 for i in range(1)]`.

(It should be noted that in `%timeit` loop, garbage collection is forced to off, so the loop made by `%timeit` does not slow down the computation.)

```
$ pip freeze | grep cupy
cupy==5.0.0b1
```
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cupy as cp

In [2]: a = cp.arange(8*16*100*100*100, dtype=cp.float32).reshape((8, 16, 100, 100, 100))

In [3]: %timeit -n100 -r10 c = [a * 2.0 for i in range(1)]
The slowest run took 5.26 times longer than the fastest. This could mean that an intermediate result is being cached.
110 us +- 89.9 us per loop (mean +- std. dev. of 10 runs, 100 loops each)

In [4]: %timeit -n100 -r10 c = [a * 2.0 for i in range(2)]
The slowest run took 40.09 times longer than the fastest. This could mean that an intermediate result is being cached.
2.66 ms +- 2.53 ms per loop (mean +- std. dev. of 10 runs, 100 loops each)
```

**Comment by beam2d** [comment]
I think the above script does not correctly measure the performance. I tried the above one, and the first run of the statement with `range(1)` returns immediately, but successive ones with even `range(1)` takes much longer time. I guess these measurements are coming from asynchronous nature of the kernel execution, and the kernel launch queue size of CUDA (which is 1,024 as I remember). While the queue is not full, the statement `a * 2.0` returns immediately. After the queue got full, it blocks until the least recent kernel finishes.

I don't think GC is related to this result. All the objects in these statements are released by reference counting, and CuPy uses a memory pool with which the above script only consumes twice of the size of `a`.

**Comment by fiarabbit** [comment]
@beam2d 
Thanks for your kind reply. I also confirmed the behavior you mentioned (rapid repeat of `range(1)` takes long time for the execution). 

However, I don't understand well the meaning of "the kernel launch queue size of CUDA". Is this mean the queue of kernel (i.e. computational operation)?
I tried smaller size of `a`, in which case the `range(1)` and `range(2)` are both fast. Does it relate to the queue-size issue?

**Comment by brandondube** [comment]
GPGPU compute is not like a CPU.  The CPU digests a sequence of machine code to perform actions and doesn't have a "queue" -- that is managed at the OS level.  On a CUDA GPU, you send the GPU a kernel (or information about a kernel) that you want it to execute, and what resource (shader data, GPGPU array, etc) you want to compute over.

CPUs have high performance execution units (cores) but not lots of them.  GPUs have low performance execution units (~= cuda core or AMD equivalent) but many many of them (on the order of a thousand).  The GPU has the task of scheduling all of them, which takes time.  This time means that while GPUs have breathtaking throughput, they have high latency.

To hide the latency, most GPU compute defaults to an asynchronous mode of operation, where when a kernel is dispatched, it is put on the GPU's queue, which it consumes as quickly as possible.  Scheduling a kernel takes 10-20 microseconds.  Executing it takes a somewhat indeterminate amount of time, depending on the current load of the GPU.  

When you dispatch thousands of kernels in short succession, the queue will fill and I believe then your async code blocks until the queue can accept another kernel.  In most normal usages, you will never experience these queue overflows, since the queue is quite large (1024 kernels it seems, from above) and most GPU workloads involve crunching 1s to 10s of much heavier kernels.

If you need to repeatedly operate on the same array, you should try `cp.fuse` to make the GPU only have to launch one kernel.

**Comment by brandondube** [comment]
Cupy has the performance characteristic where your operations, e.g. `b = 2 * a` return "immediately" after it is confirmed that the kernel is successfully scheduled.  This is usually around 20 microseconds.  Your code will only resync (i.e. block) when you try to pull data back off of the GPU.  Because you access `a` over and over and over again the GPU likely takes quite a long time to schedule the kernel in some instances, hence the 5x spread in time in the first timeit.

In the second, there is a 40x(!) spread in performance, with the fastest run taking something close to 10-20 microseconds (notice 2.66, the average, less 2.53, the stdev, leaves around 10us).  This indicates something "went wrong" on some of the attempts.

The first timeit, with 100 * 10 * 1 = 1000 kernels, likely has scheduling difficulty around use of the same array but otherwise does not fill the queue, so it remains speedy.  In the second timeit, you have 100 * 10 * 2 = 2000 kernels, which will overflow the queue, and block until it is partially emptied.  Since this is a nasty workload for a GPU, as you only access one array which prevents it from parallelizing across its SMs (~= core on a CPU, GPUs tend to have about 16 of them), you stack this slowdown with exceeding the number of pending tasks it can track.

For your (1):  Note that a CUDA kernel, at least from the perspective of the warp scheduler, is more or less anything that operates on an array.  It is true that you only have two *unique* kernels, but you still deploy one per computation.

For your (2): see above comment re: (1), you have deployed an immense number of kernels.  You can confirm that you are overflowing the queue by using, say, `%timeit -n10 -r10 ... range(10)]`  This queues the same amount of work for the GPU as the timeit with a 110us result.  Then just increase `n10` to `n20` to repeat the 2000 kernel case, and you should also observe similar timing.

**Comment by brandondube** [comment]
I was able to install VC++ build tools through my VS install.  Note that I am on cupy 5.0.0b1 w/ CUDA 9.2, which has some changes with regard to kernel launch and scheduling latency.    @kmaehashi I do not mean to take your time on this issue, but cupy 5b compiles fine with MSVC++ 14 build tools and CUDA 9.2.  A note about this may be added to cupy, or cuda 9.2 added to the build matrix, etc.

For prep, I used your line `a = cp.arange(8*16*100*100*100, dtype=cp.float32).reshape((8, 16, 100, 100, 100))` in a jupyter notebook.

Then I ran

```python
>>> %timeit -n100 -r10 c = a * 2

The slowest run took 89.71 times longer than the fastest. This could mean that an intermediate result is being cached.
365 µs ± 916 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
```
Note that in this case, there are 1000 computations done.
I then increased `n` by a factor of 10:

```python
>>> %timeit -n1000 -r10 c = a * 2

The slowest run took 289.74 times longer than the fastest. This could mean that an intermediate result is being cached.
10.6 ms ± 3.68 ms per loop (mean ± std. dev. of 10 runs, 1000 loops each)
```

What is perhaps more interesting is the system monitor during execution:

![cpu and gpu graph during execution](https://i.imgur.com/iLiRkCw.jpg)

Windows' monitor spans 60 seconds.  The initial load on the GPU is the first case with with n100.  The second spike in GPU usage and CPU usage is the run with n1000.  You can see the CPU runs out of work long before the GPU, and in fact GPU computation runs for another minute or so.

If I poke around the total kernels << 1000 space,

```python
>>> %timeit -n1 -r10 c = a * 2
The slowest run took 11.73 times longer than the fastest. This could mean that an intermediate result is being cached.
108 µs ± 116 µs per loop (mean ± std. dev. of 10 runs, 1 loop each)
```

```python
>>> %timeit -n10 -r10 c = a * 2
The slowest run took 4.01 times longer than the fastest. This could mean that an intermediate result is being cached.
68.2 µs ± 29.2 µs per loop (mean ± std. dev. of 10 runs, 10 loops each)
```

```python
>>> %timeit -n50 -r10 c = a * 2
49.2 µs ± 8.74 µs per loop (mean ± std. dev. of 10 runs, 50 loops each)
```

```python
>>> %timeit -n90 -r10 c = a * 2
55.7 µs ± 23.5 µs per loop (mean ± std. dev. of 10 runs, 90 loops each)
```

Things are constant time as expected.  I will not bore you with more outputs, but even at `-n100 -r10`, things are fine with ~50us time.

At `-n103 -r10`, 1030 kernels, just above the magic number 1024, I get this:

```python
>>> The slowest run took 118.50 times longer than the fastest. This could mean that an intermediate result is being cached.
3.42 ms ± 4.86 ms per loop (mean ± std. dev. of 10 runs, 103 loops each)
```

If you take the prior time, ~50us, multiply by ~120, then you would have 6ms which is inline with the 3.42+/- 4.86.  This does not happen with `-n102 -r10`.

Is there a reason you want to dispatch so many kernels in so short a time on a single GPU?  My CPU takes 122ms to do the same c = a * 2, even with MKL and all the other goodies helping it out as much as possible, so I understand the desire to use a GPU (1000x increase in performance, nice!) but I think in your real workload you probably can use `cp.fuse` or hand rewrite some of your steps as fused kernels and get rid of this problem.

There may also be a way with nVidia's tools to increase the kernel queue size, but you likely cannot achieve e.g. factor of ten increase there, as the warp scheduler is a very low power subsystem of the GPU.

**Comment by kmaehashi** [comment]
>  @kmaehashi I do not mean to take your time on this issue, but cupy 5b compiles fine with MSVC++ 14 build tools and CUDA 9.2. A note about this may be added to cupy, or cuda 9.2 added to the build matrix, etc.

Thanks for the heads-up! We're going to release Windows wheels for CUDA 9.2 in the next release.

**Comment by kmaehashi** [comment]
@fiarabbit Can I close this issue?

**Comment by fiarabbit** [comment]
@brandondube 
I totally understood why the queue was stacked by the 1024~ kernels.
Thank you very much for your kind reply and thoughtful explanation.

@kmaehashi 
As I understood why my code is so slow, so this issue can be closed.
(I'll close this issue.)
