### ISSUE TITLE
CudaErrorUknown

### ISSUE THREAD

**Issue by sunnydai** [cupy/cupy#1351]
When i test the cupy as the given sample, once i write the command 'x = cp.arange(6).reshape(2,3).astype('f')', the error 'cupy.cuda.runtime.CUDARuntimeError:cudaErrorUnknown:unknown error' will occur

**Comment by kmaehashi** [comment]
Thanks for the feedback.
It seems this is the issue of your CUDA installation.
Please try reinstalling CUDA.
Also make sure that Requirements are satisfied. https://docs-cupy.chainer.org/en/latest/install.html#requirements

**Comment by hmaarrfk** [comment]
I'm getting the same error on Fedora 28, x64. I have a feeling it is because fedora was really aggressive on their version of gcc and moved on to version 8, breaking alot of backward compatbility.

For what its worth, nvidia only supplies cuda 9.1 for fedora 25, which has been End of Life for a while.
They have Cuda 9.2 for fedora 27.

**Comment by hmaarrfk** [comment]
My particular errror was related to hybrid graphics.

by running my program with `optirun ipython`

I was able to run his particular line of code.

**Comment by kmaehashi** [comment]
Thanks for sharing the information!
