### ISSUE TITLE
Higher order interpolation modes in future (v5.0) map_coordinates function

### ISSUE THREAD

**Issue by jvoor** [cupy/cupy#1523]
I realize I am jumping the gun here but I noticed that in the future CuPy v5.0 you aim to implement scipy's map_coordinate function. I am very excited for this as my code spends a lot of its time in that function at present. 

I noticed that you also state that spline orders higher than 1 (linear) will not be supported initially but you aim to implement these higher orders at a later stage. Just putting my hand up now to show that at least one person is interested in this functionality. This library has already given 5-6 fold performance boosts on my ffts. So thanks very much!

**Comment by not522** [comment]
Thank you for your comment.
It is good to implement higher order interpolation, however, it is in a difficult situation because SciPy's one will be changed (See scipy/scipy#8465). I think that it is better to implement it after SciPy's one is fixed.

**Comment by grlee77** [comment]
I have started working on this. So far, I have implemented the spline prefiltering functions `spline_filter1d` and `spline_filter` using `RawKernel`. These now pass the test cases from SciPy.

The remaining step is performing the higher order interpolation, but this should be a relatively straightforward extension to the kernels proposed in #3166.

**Comment by PolarBean** [comment]
Did this make it into the project? Im really interested in using a cupy CubicSpline. Awesome work, cupy helps me and my colleagues regularly.

**Comment by grlee77** [comment]
> Did this make it into the project? Im really interested in using a cupy CubicSpline. Awesome work, cupy helps me and my colleagues regularly.

There is a preliminary implementation available at [cupyimg](https://github.com/mritools/cupyimg), but this is not an officially supported project. The intention is to make PRs here for the handful of things that are currently in `cupyimg.scipy`, but not yet present here in `cupyx.scipy`. We have also made preliminary plans to move the scikit-image related functions from `cupyimg.skimage` to a new `RAPIDS/cuImage` project, although I don't have a timeline for that yet. 

That said, if you want to try out and/or help with this initial implementation, you would just import the desired function from `cupyimg.scipy.ndimage` instead of `cupyx.scipy.ndimage`. The package is not currently on PyPI, so you would have to install directly from GitHub using something like: `python -m pip install git+https://github.com/mritools/cupyimg.git`.

One caveat is that the relative acceleration over SciPy for the nearest and linear interpolation functions as currently available here are substantially greater than the acceleration of spline order 3-5.  I get only around 10x speedup over SciPy for the spline cases and think this may be due to excessive register use in the kernels, but I have not profiled it in detail.  There is probably some further optimization that could be done.

**Comment by PolarBean** [comment]
Thank you for a detailed answer, I'll try and implement these and give you feedback on how I go.

**Comment by grlee77** [comment]
Work on fixing the boundary handling upstream in SciPy has begun. See for example: scipy/scipy#12767 and meta-issue scipy/scipy#12773

I plan to make corresponding PRs here in the future.

**Comment by fischcheng** [comment]
I'm on the same boat, we have a program that uses `map_coordinates` extensively, was very happy when I saw `cupy` and `jax` both support `map_coordinates` but realized both only up to order=1 interpolation. 

Happy to see the new boundary/model in SciPy, and currently reading through the #4402. Would love to know more details and how could similar thing can be ported to `jax`. Thanks for the great work!
