### ISSUE TITLE
multi-gpu gemm

### ISSUE THREAD

**Issue by ZhijianChan** [cupy/cupy#1583]
Is it possible to do parallel gemm computation with GPUs?

**Comment by okuta** [comment]
CuPy does not provide parallel gemm computation.
But, CuPy support multithread programming. The each treads can use each GPU as parallel.

**Comment by ZhijianChan** [comment]
Hi @okuta , [here](https://gist.github.com/ZhijianChan/14a2058cb6b184da8a5baf6a586055d9) are some snippets I use and some observations.

**Comment by okuta** [comment]
Thanks. I will check this weekend.

**Comment by okuta** [comment]
That overhead is caused by profiler (Please see Profiling Over head line). I have no idea to resolve this problem. But, there are maybe no overhead without nvprof.

I tested [this code](https://gist.github.com/okuta/974ce06d3a86ccba84af14fb6d18dcb5).

![image](https://user-images.githubusercontent.com/7133388/45250503-424ec380-b36f-11e8-87ea-555cf065dc16.png)

**Comment by ZhijianChan** [comment]
I see. Thx a lot :)

**Comment by okuta** [comment]
Thanks too!
