### ISSUE TITLE
`cupy.nextafter` is wrong on a=0

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#1686]
`test_nextafter_combination` is failing.

`{'dtype_b': <type 'numpy.float32'>, 'dtype_a': <type 'numpy.bool_'>}`
```
x          = array([[1.1754944e-38, 1.0000001e+00, 1.1754944e-38],
       [1.0000001e+00, 1.1754944e-38, 1.0000000e+00]], dtype=float32)
y          = array([[1.4012985e-45, 1.0000001e+00, 1.4012985e-45],
       [1.0000001e+00, 1.4012985e-45, 1.0000000e+00]], dtype=float32)
```

**Comment by gwtnb** [comment]
This bug may be caused by [`-ftz=true`](https://github.com/cupy/cupy/blob/04fb189ebc8cc7e4709fb505808fc084de0fccdf/cupy/cuda/compiler.py#L129).

**Comment by grafi-tt** [comment]
I agree with @gwtnb, but for me the behaviour of CuPy is correct. It seems what's wrong is the test.

The number ~1e-38 is the minimum positive normalized IEEE754 fp32 number. (It's `numpy.finfo(numpy.float32).tiny` as well as `FLT_MIN` in C on most of modern platforms.) The other number ~1e-45 is the denormalized one.

It seems the best option is to create an equality test that equates a positive (resp. negative) denormalized number on CPU with `0.0` or `FLT_MIN` (resp. `-0.0` or `-FLT_MIN`) on GPU.

Obviously you can't flush denomrlized numbers to 0 for this case. But flushing denormalized numbers to `FLT_MIN` is also wrong, because `xp.nextafter(xp.array([1.1754944e-38], dtype=`float32`))` is non-zero with Numpy and zero with CuPy. Manually setting rounding mode of a CPU is not portable.

As CuPy sets `-ftz=true`, its behaviour is reasonable. NumPy is also correct, because most of modern CPUs handle denormalized numbers by default. There is a similar discussion at StackExcahge. https://scicomp.stackexchange.com/questions/23191/implementing-stdnextafter-should-denormals-are-zero-mode-affect-it-if-so-ho
