### ISSUE TITLE
Customized output size for cupyx.scipy.ndimage.affine_transform~

### ISSUE THREAD

**Issue by pmixer** [cupy/cupy#1906]
Hi Guys, 
Thx for open sourced cupy, I was trying to use its builtin api to replace cv2.resize as stated above, but the execution reported `ValueError: total size of new array must be unchanged`, is the argument `output_shape` just a placeholder to keep it consistent with scipy API or there are tricks to get it work?
THX!

**Comment by PeterHuang2015** [comment]
@okuta @unnonouno  (try my luck to contact maintainers for the solution :see_no_evil:  THX!

**Comment by okuta** [comment]
Can you send your test code or/and long exception result?

**Comment by PeterHuang2015** [comment]
> Can you send your test code or/and long exception result?

Info provided as below, pls help double check if its my fault or a real bug, thx! Hope to perform resize and assign output directly to a pre-constructed array(shape of resized image) for further processing, thx!

Thx okuta, it was using python2 in a separate conda env and installed cupy version `6.0.0b1`, tried to use cupyx to resize a given image(opencv mode). Tried scipy and it works, cupyx.scipy also do the job but return a fixed size output which is same to the input shape, test code  as below:

```python
import cupyx
import cupyx.scipy.ndimage
import cv2
im = cv2.imread('320x180.jpg')
import cupy as cp
M = cp.eye(4)
M[0][0] = M[1][1] = 0.5
d_im_resized = cupyx.scipy.ndimage.affine_transform(d_im, M, mode='opencv')
d_im_resized = cupyx.scipy.ndimage.affine_transform(cp.array(im), M, mode='opencv')
cv2.imwrite('default.jpg', cp.asnumpy(d_im_resized)) # worked but output shape is rigid

d_im_resized = cupyx.scipy.ndimage.affine_transform(cp.array(im), M, mode='opencv', output_shape=(im.shape[0]//2, im.shape[1]//2)) # failed see info as below
d_im_resized = cupyx.scipy.ndimage.affine_transform(cp.array(im), M, mode='opencv', output=cp.zeros((im.shape[0]//2, im.shape[1]//2, 3))) # failed see info as below
```

errors reported as
```
>>> d_im_resized = cupyx.scipy.ndimage.affine_transform(cp.array(im), M, mode='opencv', output_shape=(im.shape[0]//2, im.shape[1]//2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pmixer/anaconda3/envs/py2/lib/python2.7/site-packages/cupyx/scipy/ndimage/interpolation.py", line 242, in affine_transform
    prefilter).reshape(output_shape)
  File "cupy/core/core.pyx", line 581, in cupy.core.core.ndarray.reshape
  File "cupy/core/core.pyx", line 565, in cupy.core.core.ndarray._reshape
ValueError: total size of new array must be unchanged
>>> d_im_resized = cupyx.scipy.ndimage.affine_transform(cp.array(im), M, mode='opencv', output=cp.zeros((im.shape[0]//2, im.shape[1]//2, 3)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pmixer/anaconda3/envs/py2/lib/python2.7/site-packages/cupyx/scipy/ndimage/interpolation.py", line 240, in affine_transform
    ret = _get_output(output, input, output_shape)
  File "/home/pmixer/anaconda3/envs/py2/lib/python2.7/site-packages/cupyx/scipy/ndimage/interpolation.py", line 14, in _get_output
    raise ValueError("output shape is not correct")
ValueError: output shape is not correct
```

original and default output image(could not get reshaped image without black paddings due to errors although scipy worked, had to pass M in cupyx but could pass (0.5, 0.5) as second parameter in scipy):
![320x180](https://user-images.githubusercontent.com/13297503/50468666-115cd200-09e4-11e9-8438-8f9a36e052a5.jpg)

![default](https://user-images.githubusercontent.com/13297503/50468673-19b50d00-09e4-11e9-8b45-8d73ba9c9fb5.jpg)

**Comment by PeterHuang2015** [comment]
Sorry guys, I tried hard but could not find my original scipy script, tried cupy again and found it's my fault, `output_shape` and `output` should be specified together(hope this could be added in error prompt or in docstring), otherwise may lead to errors. Hope the [official doc](https://docs-cupy.chainer.org/en/v5.1.0/reference/ndimage.html?highlight=resize#module-cupyx.scipy.ndimage) could be updated to elaborate how to resize an image using cupyx like this approach:

```python
import cupyx
import cupyx.scipy.ndimage
import cv2
import cupy as cp

im = cv2.imread('320x180.jpg')

M = cp.eye(4)
M[0][0] = M[1][1] = 0.5

smaller_shape = (im.shape[0]/2, im.shape[1]/2, 3)
smaller = cp.zeros(smaller_shape)
smaller = cupyx.scipy.ndimage.affine_transform(im, M, output_shape=smaller_shape, output=smaller, mode='opencv')
cv2.imwrite('smaller.jpg', cp.asnumpy(smaller)) # worked but output shape is rigid
```

Sorry for the mistake with a mess in my head.:runner:, cupy is cool:beer:

regards,
Peter

**Comment by PeterHuang2015** [comment]
submitted a pull request for updating doc on this issue.

**Comment by PeterHuang2015** [comment]
Hi @not522 , thx for the response! I need to preallocate memory for the resized image which is why I passed smaller for `output`, the `smaller = ` is kind of extra stuff in this case.

May I know which one among `zoom` and `affine_transform` would you recommend for resizing the image to a fixed size?

In memory, I failed few times when only specifying output_shape (without output), gonna to test it tomorrow.

THX!

**Comment by not522** [comment]
Sorry for late reply. I think always `zoom` is recommended for resizing. Both are very similar but slightly different for interpolation.

```
a = np.asarray([[1, 3, 5, 7]], dtype=np.float32)
M = np.asarray([[0.5, 0, 0], [0, 1, 0]])
print(cv2.resize(a, dsize=(2, 1)))
print(cv2.warpAffine(a, M, dsize=(2, 1)))
```
```
[[2. 6.]]
[[1. 5.]]
```

**Comment by not522** [comment]
2021年8月12日(木) 1:15 Kenichi Maehashi ***@***.***>:
