### ISSUE TITLE
repeat() does not work with 0-d array for the number of repeats

### ISSUE THREAD

**Issue by themightyoarfish** [cupy/cupy#1918]
The following code raises a `TypeError` in `6.0.0a1`, which is unexpected to me. It appears `cupy.repeat` needs the number of repeats to be a Python integral scalar type, so it is impossible to dynamically compute the number of repeats without going through the CPU.

```
cupy.repeat(cupy.array([1, 2, 3]), cupy.array(4, dtype=int))
```

**Comment by toslunar** [comment]
On interface, it's worth supporting `cupy.ndarray` at the `repeats` arg of `cupy.repeat`.
On performance, it seems hard to me to avoid CPU because the shape of the output of `repeat` depends on the second argument and `cupy.ndarray` stores its shape on CPU.

**Comment by jpivarski** [comment]
To second this, [cupy.repeat](https://docs.cupy.dev/en/stable/reference/generated/cupy.repeat.html) doesn't accept an array as its second argument, which repeats each input element a different number of times in [numpy.repeat](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html):

```python
>>> data = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
>>> repeats = np.array([3, 1, 0, 2, 4])
>>> assert len(data) == len(repeats)
>>> np.repeat(data, repeats)
array([1.1, 1.1, 1.1, 2.2, 4.4, 4.4, 5.5, 5.5, 5.5, 5.5])
>>> assert len(np.repeat(data, repeats)) == np.sum(repeats)
```

Since I need this feature in a project I'm working on, this is how I implemented it in a compatibility layer (without for loops):

```python
def repeat(array, repeats):
    if isinstance(repeats, cupy.ndarray):
        all_stops = cupy.cumsum(repeats)
        parents = cupy.zeros(all_stops[-1].item(), dtype=int)
        stops, stop_counts = cupy.unique(all_stops[:-1], return_counts=True)
        parents[stops] = stop_counts
        cupy.cumsum(parents, out=parents)
        return array[parents]
    else:
        return cupy.repeat(array, repeats)
```

An implementation in CUDA could do this with fewer passes over the data, though I think a prefix sum (`cumsum`) would still be necessary.

**Comment by toslunar** [comment]
> To second this, [cupy.repeat](https://docs.cupy.dev/en/stable/reference/generated/cupy.repeat.html) doesn't accept an array as its second argument, which repeats each input element a different number of times in [numpy.repeat](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html):

Let's continue the discussion in #3849.
