### ISSUE TITLE
Support compilation via nvcc in RawKernel

### ISSUE THREAD

**Issue by sjperkins** [cupy/cupy#1928]
Currently, RawKernel utilises NVRTC to compile device code into cubins. This is great for code that only contains device code.

There are useful C++ CUDA libraries such as [cub](https://github.com/NVlabs/cub) and [trove](https://github.com/bryancatanzaro/trove) that contain device, block and warp wide primitives (scan, transpose, reduce etc.) that are useful for CUDA programmers in general.

Unfortunately it is not currently possibly to use these libraries with NVRTC as it does not automatically include system headers. For example, see:

- https://devtalk.nvidia.com/default/topic/1028233/include-header-in-nvrtc/
- https://stackoverflow.com/questions/50565200/including-c-standard-headers-in-cuda-nvrtc-code

There's an issue requesting NVRTC compatibility from cub (https://github.com/NVlabs/cub/issues/131) due to these problems, but in the mean time it would be useful to work around this by allowing RawKernel to compile code via nvcc (perhaps using the functionality in install/*.py)

**Comment by leofang** [comment]
There is already a workaround as discussed in #1657 if you don't mind compiling your CUDA codes externally and then loading the resulting `.cubin` files in CuPy. In my experience, in a high-performance computing environment involving MPI and job schedulers like Slurm, spawning additional processes like NVCC could be problematic, which is why I was convinced in that issue to use `RawKernel`. Also, there is a pending PR #1889 providing a `RawKernel.compile()` method (which still uses NVRTC). However, I agree that maybe in some other use cases calling NVCC is more appropriate. Let's hear out what core devs have in mind.

**Comment by sjperkins** [comment]
I should have been clearer: I'm not suggesting NVCC replace NVRTC as the default case, but it would be useful as a different backend for RawKernel in cases where 3rd party libraries cause difficulties.

I've hacked something together, I may put a PR together for this.

**Comment by leofang** [comment]
Closed by #1941.

**Comment by leofang** [comment]
@niboshi This is closed by #1941.

**Comment by niboshi** [comment]
Right. Thanks!
