### ISSUE TITLE
Unexpected result in cupy.divide with dtype argument

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#2059]
Version: current master 202e4e8902e593b8c8ba487f8371e4b6a42e4660
```
>>> cupy.show_config()
CuPy Version          : 6.0.0b2
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9020
CUDA Driver Version   : 9020
CUDA Runtime Version  : 9020
cuDNN Build Version   : 7005
cuDNN Version         : 7005
NCCL Build Version    : 2104
NCCL Runtime Version  : (unknown)
```

#### Code
```py
import cupy
import numpy

a = cupy.array(500., dtype=numpy.float64)

c = cupy.divide(1., a)
print(c.dtype, c)

c = cupy.divide(1., a, dtype=numpy.float64)
print(c.dtype, c)
```
#### Result
```
float64 0.002
float64 -0.08333333333333333
```

**Comment by fiarabbit** [comment]
I also succeeded to reproduce the situation, which is not observed in `numpy`.

**Code w/ numpy**
```numpy.py
import cupy
import numpy

a = numpy.array(500., dtype=numpy.float64)

c = numpy.divide(1., a)
print(c.dtype, c)

c = numpy.divide(1., a, dtype=numpy.float64)
print(c.dtype, c)
```
**Result w/ numpy**
```output.py
float64 0.002
float64 0.002
```

**Comment by grafi-tt** [comment]
@fiarabbit @niboshi 

This behavior happens as 500.0 is casted to `signed char`. The result of cast is -12, due to modulo 256 arithmetic and 2-complement representation. Then 1 / -12 is `-0.08333333333333333`.

This undesired cast occurs only on CuPy, because NumPy's type resolution via `dtype` argument checks whether input is castable.

* https://github.com/numpy/numpy/blob/v1.16.2/numpy/core/src/umath/ufunc_type_resolution.c#L1632-L1636
* https://github.com/numpy/numpy/blob/v1.16.2/numpy/core/src/umath/ufunc_type_resolution.c#L2242-L2244
* https://github.com/numpy/numpy/blob/v1.16.2/numpy/core/src/umath/ufunc_type_resolution.c#L184-L186
* https://github.com/numpy/numpy/blob/v1.16.2/numpy/core/src/umath/ufunc_type_resolution.c#L1098-L1102

I don't have spare time to submit a PR for a while, so feel free to fix.

**Comment by grafi-tt** [comment]
I checked the kernel cache using `CUPY_CACHE_SAVE_CUDA_SOURCE=1` on CuPy 5.0.0.

```
#include <cupy/complex.cuh>
#include <cupy/carray.cuh>
#include <cupy/atomics.cuh>

    typedef signed char in0_type;
typedef signed char in1_type;
typedef double out0_type;

    extern "C" __global__ void cupy_true_divide(const signed char in0, const CArray<double, 0> _raw_in1, CArray<double, 0> _raw_out0, CIndexer<0> _ind) {
      ;
      CUPY_FOR(i, _ind.size()) {
        _ind.set(i);
        const in1_type in1(_raw_in1[_ind.get()]);
out0_type &out0 = _raw_out0[_ind.get()];
out0 = (out0_type)in0 / (out0_type)in1;
      }
      ;
    } 
```

Probably we have to fix `_guess_routine_from_dtype` function on `_kernel.pyx`.

**Comment by okuta** [comment]
This is cause of issue.
```
>>> cupy.true_divide.types
[u'bb->d', u'BB->d', u'hh->d', u'HH->d', u'ii->d', u'II->d', u'll->d', u'LL->d', u'qq->d', u'QQ->d', u'ee->e', u'ff->f', u'dd->d', u'FF->F', u'DD->D']
>>> numpy.true_divide.types
['ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mq->m', 'md->m', 'mm->d', 'OO->O']
```
