### ISSUE TITLE
Support CUDA 10.1 & cuDNN 7.5

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#2069]

**Comment by Naba7** [comment]
CUDA 10.1 supports cuDNN 7.5 and NCCL 2.4.2.It is not written in the documention.I have checked on my machine with Ubuntu 18.04LTS and is working fine.I have prepared a blog-post describing how to download CUDA10.1,cuDNN 7.5 along with NCCL 2.4.2. Shall I update installation.rst because there only CUDA10.0 is there. #2069

**Comment by kmaehashi** [comment]
@Naba7 Sorry for not responding, and thank you for your contribution! We needed some fixes other than documentation to support them. See #2117 for details.

**Comment by kmaehashi** [comment]
Implemented in #2117
