### ISSUE TITLE
Adding equivalent filters from scipy.ndimage.filters

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2099]
Would be great to support some common filters from [`scipy.ndimage.filters`]( https://docs.scipy.org/doc/scipy-1.0.0/reference/ndimage.html#module-scipy.ndimage.filters ). Having `convolve`, `correlate` and `generic_filter` would be great and allow users to build up many common convolutions with relatively little work using a familiar API. There are others that would be very nice as well.

**Comment by kmaehashi** [comment]
Thanks for the feature requests.
We always welcome contributions for such missing features!
https://docs-cupy.chainer.org/en/latest/reference/comparison.html#multidimensional-image-processing

**Comment by grlee77** [comment]
Hi @jakirkham. Do you have an immediate need for this or a particular use case in mind?

I recently implemented the equivalent of `ndi.convolve` (built using a GPU-based implementation of  `scipy.signal.upfirdn(..., up=1, down=1)` under the hood) that supports float32, float64, complex64 and complex128. I haven't tried to make a PR for it here or posted it publicly, but can share it if you are interested in collaborating on it.

I implemented `scipy.signal.upfirdn` using CuPy and added support for various signal extension modes at the boundary (not currently available in SciPy's `upfirdn`). In my case, I started implementing a library expanding the functionality in PyWavelets. The version of `upfirdn` I have currently only supports downsampled convolution with `up=1, down=M` or upsampled convolution with `up=M, down=1` as those were the only cases I needed for M-band wavelet filterbanks. With a bit more effort, it could be updated to allow the general setting of any positive integer `up`, `down` and become suitable for a PR here.

**Comment by jakirkham** [comment]
Not immediate, but it is something I can see use cases coming up for.

That does sound interesting. Yeah, if you would be willing to share, it would be great to discuss.

Ah ok. Thanks for the context. Is this in PyWavelets currently or in a library built on top of it?

**Comment by jakirkham** [comment]
Just as another thought, it might be worth looking at how [`chainer.functions.convolution_nd`]( https://docs.chainer.org/en/stable/reference/generated/chainer.functions.convolution_nd.html ) is implemented. Likely much of that code could be reused here as well. Perhaps even simplified a bit as this has fewer features.

**Comment by grlee77** [comment]
Yeah, that would be a good place to look for general n-dimensional convolution. 

One thing I forgot to mention is that my implementation is really only for separable filters at the moment (i.e. like applying `ndimage.convolve1d` along each axis in turn). So it can do the equivalent of `ndimage.uniform_filter`, `ndimage.gaussian_filter` or separable filtering along axes as used in the DWT, but does not support general n-dimensional kernels. It is not currently online, but when I get a chance I will post what I have in a standalone repo and put a link here for reference.

**Comment by grlee77** [comment]
Looking into the Chainer implementation a bit, there appear to be two different underlying GPU implementations. When cuDNN is available, it uses `cupy.cudnn.convolution_forward` which relies on Nvidia's cuDNN library. Otherwise it falls back to the implementation in [chainer/util/conv_nd.py](https://github.com/chainer/chainer/blob/master/chainer/utils/conv_nd.py).

**Comment by jakirkham** [comment]
Would be curious if you have thoughts on this, @anaruse?

**Comment by mrocklin** [comment]
@jakirkham @pentschev , do you have a sense for how long it would take to build out the core operations necessary for a couple of important/common user operations?  What would be a good time investment to see if this approach has promise?

**Comment by jakirkham** [comment]
My (albeit naive) approach to this problem would be (looking at the [SciPy's `convolve` docs]( https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.ndimage.convolve.html#scipy.ndimage.convolve )).

1. Only allow the default `origin` (so `0`) initially.
2. Handle the `mode` and `cval` parameters through [CuPy's `pad`]( https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.pad.html ).
3. Worry only about the case where cuDNN is available.
4. Write a few tests making sure this implementation lines up with SciPy's and what one would naively expect for base cases.

This should cut out some parts that may take time and we may not be too worried about on the first pass. Should add this does mean we probably don't handle all padding modes that SciPy handles (at least not initially). It also means we may not benefit from some more performant ways to handle padding with cuDNN initially. Finally it means that users will need cuDNN to get this to work.

Once we have this done and have a good rough idea of how this performs, it would be good to determine the value of handling padding with cuDNN directly. Also it would be beneficial for users to port any fallback code for when cuDNN is not present.

Following this we will want some user feedback to determine how we prioritize functionality we left out on the first or second pass. It would also be good to determine whether things can be made faster.

**Comment by jakirkham** [comment]
To get a sense of how complicated this might be to do (given the rough plan above), I tried just using CuPy and Chainer as-is to mimic SciPy's `convolve`. Was able to come up with a [short notebook]( https://gist.github.com/jakirkham/2c66b096d472054ccb1c9556bad9601a ) that has a working first pass of this functionality.

**Comment by jakirkham** [comment]
> Should add this does mean we probably don't handle all padding modes that SciPy handles (at least not initially).

It's worth noting that PR ( https://github.com/cupy/cupy/pull/2399 ) is overhauling CuPy's `pad` and adding the functionality that was missing when compared to NumPy's `pad`. So this may help up handle any other padding cases we want.

**Comment by pentschev** [comment]
Those points look good to me @jakirkham, I agree that the best is to start with a minimal set of requirements and expand in a future iteration if/when needed.

**Comment by grlee77** [comment]
I finally got around to cleaning things up and making a public repo for some of the things I mentioned about a year ago (better late than never!). A CPU + GPU implementation of `upfirdn` is in the [fast_upfirdn](https://github.com/mritools/fast_upfirdn) package. It differs from the implementation in [cusignal](https://github.com/rapidsai/cusignal) in that the GPU implementation uses `cupy.RawKernel` instead of `Numba`.

Building on top of this, [cupyimg](https://github.com/mritools/cupyimg) implements a ton of other functions, primarily from `scipy.ndimage`, `scipy.signal` and `scikit-image`. 

I have been working on getting some `scipy.ndimage` and NumPy stuff that was needed implemented as PRs here so that they can benefit from better code review and CI testing. Currently `cupyimg` does not have CI and I have just been running tests locally on linux. There are quite a few tests copied from the corresponding CPU-based packages, but these do not typically conform to the CuPy style, so getting things ready for PR here would still require quite a bit of work. There is also a substantial amount of kernel code duplication that could be avoided by refactoring of the type done by @coderforlife in #3184.

I think `scikit-image` functions are out of scope for CuPy itself. I'm not too sure about the viability of maintaining a parallel fork long-term without obtaining any official funding/support to do so, but wanted to try out at least a subset of the library that is built on top of `scipy.ndimage` functions.

**Comment by mrocklin** [comment]
Whoa.  

I don't know this space well, but this seems like everything that people here were asking for?  If so, then this is great?

https://github.com/mritools/cupyimg#available-functions

**Comment by mnicely** [comment]
@grlee77 I submitted a PR to rapidsai/cusignal for CuPy raw kernel implementation for upfirdn (1d) version yesterday https://github.com/rapidsai/cusignal/pull/31. I'd be interested to see the performance difference.

**Comment by mnicely** [comment]
@jakirkham I just saw your comments on using `cupy.pad`. While it can be used, I found that instead doing the math inside the kernel itself instead of call `pad` beforehand provided 2x improvement in performance. See https://github.com/rapidsai/cusignal/pull/62.
