### ISSUE TITLE
Linux build 5.4.0 is missing

### ISSUE THREAD

**Issue by asyd** [cupy/cupy#2135]
Hi,

I want to install cupy-cuda92==5.4.0 (which is an explicit dependency from `spacy[cuda92]`) but I notice there is no linux build available on pypi.

https://pypi.org/simple/cupy-cuda92/

Only

* cupy_cuda92-5.4.0-cp36-cp36m-win_amd64.whl
* cupy_cuda92-5.4.0-cp37-cp37m-win_amd64.whl

Are available for 5.4.0

Are there some particular reasons?

Thanks

**Comment by kmaehashi** [comment]
We are currently unable to upload wheels for CUDA 9.2 and 10.1 due to the file size limitation of PyPI, and contacting with PyPA team to resolve the issue. (https://github.com/pypa/warehouse/issues/5665)

https://github.com/cupy/cupy/releases/tag/v5.4.0
> Note: CuPy wheels (pre-compiled binary packages) for CUDA 9.2 (cupy-cuda92) and 10.1 (cupy-cuda101) of this version are currently not available. We are planning to release it in a few days.

v5.4.0 / v6.0.0rc1 wheels for CUDA 8.0/9.0/9.1/10.0 are already released on PyPI.
Sorry for the inconvenience.

**Comment by asyd** [comment]
Thanks for you reply!

**Comment by kmaehashi** [comment]
Just released CUDA 9.2 and 10.1 wheels.
