### ISSUE TITLE
CuPy not accepting list data types for operations

### ISSUE THREAD

**Issue by TanishSharrma** [cupy/cupy#2138]
For any function on a list(array) data type, Cupy gives an error unless the array has been defined as a cupy.array(). In, numpy however, the list data type is accepted regardless of it being passed as numpy.array() or not.

a = [10,15]
b = cupy.log(a)

This won't work in Cupy but will work in Numpy. a = cupy.array([10,15]) would work. 
TypeError: Unsupported type <class 'list'>
This could cause problems for people shifting from Numpy to Cupy.

**Comment by txuh** [comment]
Convert a to numpy liked cupy array first; then compute the log.

a=cupy.asarray(a)
b=cupy.log(a)

**Comment by TanishSharrma** [comment]
@txuh What I mean is that in numpy, functions can be executed on lists without defining the list as numpy.array(), however in cupy, an error arises if the array is not defined as cupy.array() : "TypeError: Unsupported type <class 'list'>".
Example :
a = [10,15]
b = numpy.log(a)
c = cupy.log(a)

The numpy part of the code (b) would work but the cupy part (c) won't and since we are trying to incorporate all of numpy function in cupy, I thought this was worth discussing as an issue. Also, people shifting from numpy to cupy might encounter this error more often than we think.

**Comment by leofang** [comment]
Related: #594

In #1947, the decision was made that we always pass the arguments to `cupy.asanyarray` internally before the actual computation so that lists can be used, see https://github.com/cupy/cupy/blob/83aec55e8c10c6fcbbe2edb48e3d21c9cfb92e86/cupy/logic/comparison.py#L94-L95 While this is in line with how `numpy.allclose` was implemented, I am not sure whether this practice is good. From the performance viewpoint an internal cast is unwanted, especially if the function is to be called like a million times.
