### ISSUE TITLE
floating point errors

### ISSUE THREAD

**Issue by casperdcl** [cupy/cupy#2248]
Odd discrepancies for simple maths without overflow potential where there shouldn't really be disagreement

```bash
nvidia-docker run --rm -it cupy/cupy /bin/bash -c python
```
```python
import numpy as np
import cupy as cp
b = np.arange(1e3, dtype='float64'); b2=(b**2-b-5)/2.0
a = cp.arange(1e3, dtype='float64'); a2=(a**2-a-5)/2.0
print((a2==cp.array(b2)).mean().item())
0.937  # should be 1
cp.show_config()
```
```
CuPy Version          : 7.0.0a1
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9020
CUDA Driver Version   : 10010
CUDA Runtime Version  : 9020
cuDNN Build Version   : 7402
cuDNN Version         : 7402
NCCL Build Version    : 2402
NCCL Runtime Version  : 2402
```

**Comment by kmaehashi** [comment]
In CuPy v7.0.0a1, `**` operator calls `pow` function. https://github.com/cupy/cupy/blob/v7.0.0a1/cupy/core/_routines_math.pyx#L403-L417

Due to the limitation of CUDA, computations results on the device may include error. Error bounds for each function are documented in the following page:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#standard-functions
> pow(x,y) | 2 (full range)

We will change `**` to avoid using `pow`, so this behavior may change in the future (next) releases. (see #2204 for details)

**Comment by casperdcl** [comment]
Didn't realise you wanted a response.

#2204 is unrelated.

Other libraries such as tensorflow-gpu have put effort into ensuring results match the cpu implementions (e.g. convolving with tensorflow or tensorflow-gpu or numpy produces the same values, even including precision errors)
