### ISSUE TITLE
[RFC] Introduce a configuration mechanism

### ISSUE THREAD

**Issue by hvy** [cupy/cupy#2436]
There is no mechanism in CuPy to give the user (thread local) control over various behaviors in CuPy e.g. how to trade off performance vs debuggability/NumPy compatibility on a routine-level. This is not an issue for most of the routines, but there are cases where this matters. 

1. Allow synchronous CUDA kernel calls to report proper errors (e.g. check ndarray values or device status codes to report errors similar to NumPy) instead of writing special values or have UB. https://github.com/cupy/cupy/issues/2414
1. Allow slower execution but deterministic results (e.g. CUB).
1. NumPy fallback mode (Cc. @asi1024)

How about introducing some configuration mechanism to CuPy? This would incur some overhead to existing code but would make CuPy more usable.

**Comment by asi1024** [comment]
I want to support a `cupy.errstate` class which has the same API as `numpy.errstate`, but it can handle only floating-point errors. So, how about supporting additionally `cupyx.errstate` as an extension of `cupy.errstate`? In my mind, `cupyx.errstate` will have more keyword arguments than `{numpy/cupy}.errstate` (e.g., `linalg`)

**Comment by kmaehashi** [comment]
Another use-case for configuration is `cupy.fft.config.enable_nd_planning`:
* https://github.com/cupy/cupy/blob/v7.0.0b3/cupy/fft/config.py
* https://docs-cupy.chainer.org/en/v7.0.0b3/reference/fft.html#code-compatibility-features

**Comment by niboshi** [comment]
Another example this mechanism could be useful: #2505

**Comment by leofang** [comment]
Personally all I care is performance and I'm all in for making any possible performance boost default. But, from the standpoint of users migrating from NumPy or even outside the Python ecosystem, it is also important to minimize surprises. 

Based on this, I suggest to do all the syncs and checks you could possibly image, and in the documentation you create a tutorial or guideline for performance tuning (#1566) so that advanced users can find their way out.
