### ISSUE TITLE
CuPy surface support

### ISSUE THREAD

**Issue by Fokatu** [cupy/cupy#2624]
I saw that Cupy have added support to texture memory. 
Is it possiable to add surface support, such that one can read and write a cudaArray at the same time.

**Comment by leofang** [comment]
I wrote the texture support (#2432) so I feel obligated to say something 🙂

If you are interested in supporting surface memory, I'll be more than happy to give you a detailed guidance as needed. Basically, you need to expose the relevant runtime API to Python, have a few wrappers around the surface objects, and make RawKernel recognize it. Understanding how the texture memory was supported in #2432 would also be a good starting point.

Don't waste time on surface references; it's deprecated and will be removed by NVIDIA at some point. In that case you'll also need to understand the driver API, which was a bit painful to me.

That being said, I wonder if all of these are really worth your time? Given that this is the first request for surface memory I've ever seen on the issue tracker, I suspect for most of CuPy users having access to texture memory is more than enough. Do you absolutely need this? I'm asking because I found, based on #2432, that reading from texture memory on high-end GPUs (P100/V100) is actually slightly slower than reading from global memory. I guess it's because those models have a unified L1/texture cache. So for my case I just simply read/write from global memory. You can do a careful timing and decide if preparing a PR is rewarding or not.

As an enthusiastic contributor I wish I have more time to prepare a PR for this. Unfortunately this is not my priority, especially given my observation for performance. Again, I'll be happy to help should you be brave enough to accept the challenge! 😄

**Comment by Fokatu** [comment]
@leofang ,thank you for your reply. Based on your code and a short learning of Cython, I have implemented the support of Surface memory. But I am not familiar with github and who it works, I don't know how to share my modifications.

The reason I use texture is its auto interpolation function. If there is no apparent speedup, then it is better to use global memory.

**Comment by leofang** [comment]
@Fokatu That was fast! You will need to submit a PR and work with the internal and external reviewers (like me) to improve it. What you need to do:
- Fork CuPy 
- Make changes locally, write some unit tests for the new features, and test them all locally
- Ensure flake8/autopep code format compliance
- Push your local changes as a new branch in your remote fork
- On GitHub, switch to the new branch and create a PR 
- Check if the CI tests are passed (if errors happen, most likely they're due to code format non-compliance)
- Address any suggestions or comments from code review

I'll try to help when I have time. The existing PRs (such as #2432) should give you a clear picture on how everything works. Also, the CuPy's contribution guide is a great resource: https://docs-cupy.chainer.org/en/latest/contribution.html.
