### ISSUE TITLE
Add ability for rawkernels and rawmodules to accept a path to ptx files in addition to cubin

### ISSUE THREAD

**Issue by HouseOfFinwe** [cupy/cupy#2779]
Cupy rawkernels and rawmodules only accept source core and paths to cubin files.  They should also accept paths to ptx files since the driver api allows for this.

**Comment by leofang** [comment]
Hi @HouseOfFinwe, in the PR #2782 I added the PTX support to `RawModule`. I believe it's the right place to support it, since for `RawKernel` it'd require more code changes, and I think based on the API design it is unintuitive to have PTX code supported there. 

FYI, your title is inaccurate, as cubin is already supported in `RawModule`.

Just curious, did you request this because you actually need this capability, or simply because the driver API allows it? As I mentioned in the PR I know there are people writing PTX directly, but that is a very, very uncommon practice afaik. In CuPy they are not aiming at 100% coverage of the driver API, but at the most useful (or commonly used) subset of it.

**Comment by HouseOfFinwe** [comment]
That was just poor phrasing on my part.  I should have said in addition to cubin.  Our kernels are compiled to ptx, so it would be useful to us if cupy supported this capability.

**Comment by leofang** [comment]
If you have the source code to compile from, why not just passing them to `RawModule`?

**Comment by HouseOfFinwe** [comment]
Because it would be a pain in the butt to provide all the include directories and compile options.  The kernels are already compiled in C++ in another project.  I would like to leverage those kernels without having to recompile them.  More driver API coverage would be nice.  I understand this is not cupy’s aim, but no one else in python land is really doing this other than perhaps pycuda, and they dont integrate as nicely with pytorch.

**Comment by takagi** [comment]
Closed via #2782.
