### ISSUE TITLE
Numba Enhancement Proposal (NBEP) 7: External Memory Management Plugins

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2976]
Raising here to solicit feedback on a proposal for External Memory Management support in [Numba]( https://numba.pydata.org ) (also called NBEP 7). Discussion is occurring in [this repo]( https://github.com/gmarkall/nbep-7 ). Please take a look and raise issues/PRs as you see fit. Thanks in advance for your feedback!

cc @gmarkall (for awareness)

**Comment by leofang** [comment]
I'm not affiliated with PFN, so it's definitely not my call 😅 But as an external contributor interested in interoperability I have a few questions:
1. For CuPy users, passing CuPy arrays to Numba's `@cuda.jit` kernels via `__cuda_array_interface__` works just fine, so what's the motivation (or advantage) for CuPy core devs to consider this proposal? 

(In my daily work, I never had to use Numba's device array after CuPy started working with Numba. Frankly speaking, the Numba array implementation is buggy to me...When I [added tests to mpi4py](https://bitbucket.org/mpi4py/mpi4py/pull-requests/16) I made a lot of effort just to make very simple operations work, so I wonder why anyone would use it now that we have CuPy...)

2. Take a step back, since this is a "Numba enhancement" proposal, shouldn't the actual implementation (subclass of `BaseCUDAMemoryManager ` or `HostOnlyCUDAMemoryManager`) be done together with the base class in Numba rather than in RMM/CuPy/etc? I feel a centralized collection of plugins supporting different libraries would be much easier to maintain (and understand) than those scattered in different libraries? 

In other words, rather than doing `rmm.use_rmm_for_numba()`, we should simply call `numba.cuda.cudadrv.driver.set_memory_manager('rmm')`, and similarly for switching to CuPy's memory manger by simply replacing `'rmm'` to `'cupy'`. Another concern along this line is that CuPy currently does not depend on Numba and it should not be.

3. This is a bit more technical: Does the `context` argument in the proposed `MemoryPointer` refer to the CUDA context (`CUcontext`)? The meaning is not clear to me. If it is, you'd need to add to the proposal how to deal with libraries that use CUDA runtime API to avoid managing contexts themselves (as in CuPy if I understand correctly). It needs to use the driver API to retrieve a handle to the current context.

4. Would there be any problem in the library initialization order? I hope swapping the order should have no impact and be equivalent:
```python
import cupy  # or rmm
from numba import cuda
```
and
```python
from numba import cuda
import cupy  # or rmm
```
Not sure if there's any device memory allocated during CuPy's initialization...

5. @jakirkham Could this NBEP be less complex now that you made RMM works with CuPy (#2635, rapidsai/rmm#198)?

Finally, just to raise awareness: CuPy core devs are considering the interoperability of its memory management with PyTorch's: #2762. Since Numba is an (optional?) dependency of PyTorch, it'd be nice to solicit feedbacks from PyTorch core devs as well?

**Comment by jakirkham** [comment]
Thanks for all of the feedback @leofang! 😄

Well from the RAPIDS perspective, users may choose to allocate arrays any number of ways. Given this, we want to make sure that we can back those allocations with the same allocator regardless of whether users chose to do this through CuPy, Numba, or possibly other things. Wasn't sure whether CuPy developers would want similar functionality. So figured we should ask 😉

(If there are buggy things with Numba's arrays, would you mind raising some issues about these bugs. We've been doing some work in this area recently 😄)

Given the exact nature of how to implement such a class for a specific library is likely outside of the Numba developers knowledge (and may need to change based on changes in those external libraries), it's probably easier to offload that work to libraries implementing the protocol themselves. Though please feel free to [raise an issue here]( https://github.com/gmarkall/nbep-7/issues ) if you'd like to discuss further 🙂

Assuming the above point is agreeable, it seems we are now discussing what an API and discoverability/registration of plugins might look like. This seems like a useful thread of discussion. Would you be willing to raise this as a separate issue on the nbep-7 repo? 😉

The dependency point is well taken. I've raised issue ( https://github.com/gmarkall/nbep-7/issues/11 ) to discuss this. Please feel free to add anything else there 🙂

I think so. Though I'm not a Numba expert. You may need to ask someone else. [This doc]( https://numba.pydata.org/numba-doc/dev/cuda-reference/host.html#context-management ) seems relevant. Do you might raising this on the nbep-7 repo?

Good question on import order. Raised as issue ( https://github.com/gmarkall/nbep-7/issues/12 ).

Agreed! It would be great to get feedback from the larger community. Will ask around. Thanks also for all of the feedback so far. Looking forward to discussing further 🙂

**Comment by gmarkall** [comment]
Many thanks for looking at the proposal and providing some really helpful feedback - @jakirkham's answers address the questions similarly to my line of thinking - I'd just like to add a couple of points:

> This is a bit more technical: Does the context argument in the proposed MemoryPointer refer to the CUDA context (CUcontext)? The meaning is not clear to me. 

The CUDA context is an instance of `numba.cuda.cudadrv.Context` - this is an object that provides access to various bits of functionality in the current context, and is documented at: http://numba.pydata.org/numba-doc/latest/cuda-reference/host.html#context-management - one of the limitations of the proposal at the moment is that I'm a bit vague about the relationship between contexts and how thrid-party libraries manage memory (as noted in https://github.com/gmarkall/nbep-7#unresolved-items). For both the RMM- and CuPy-based plugin prototypes, I've satisfied the requirement to provide the `Context` object to the `MemoryPointer` by calling `numba.cuda.current_context()` and using the result. The proposed `MemoryPointer` is in the current version of the proposal, the same as the `MemoryPointer` class that already exists in Numba - this is presently not exposed as part of the public API.


> If it is [a CUcontext], you'd need to add to the proposal how to deal with libraries that use CUDA runtime API to avoid managing contexts themselves (as in CuPy if I understand correctly). It needs to use the driver API to retrieve a handle to the current context.

For libraries that use the CUDA runtime API such as CuPy, I'd imagine that using `numba.cuda.current_context()` as the `context` argument of `MemoryPointer` would suffice for this use case - this is what I've done with an implementation of a CuPy memory pool plugin: https://github.com/gmarkall/nbep-7/blob/master/nbep7/cupy_mempool.py#L24 (note that there's some more work to do to make this prototype more complete, but it has some basic operation for now).

> Could this NBEP be less complex now that you made RMM works with CuPy (#2635, rapidsai/rmm#198)?

Part of the problem that the NBEP addresses is that even if RMM works with CuPy, Numba will still allocate its own memory outside of RMM's control - for example, taking the transpose of a `DeviceArray` will result in an allocation by Numba for the transpose result. The aim is to get Numba to do *all* memory allocation through a third-party library, rather than just for interoperability between libraries that each do their own allocation (as is solved by `__cuda_array_interface__` now, which you mention in (1.) above).

So, to answer the question, I don't see a way to reduce the complexity of the proposal based on using CuPy with RMM.

> Finally, just to raise awareness: CuPy core devs are considering the interoperability of its memory management with PyTorch's: #2762. Since Numba is an (optional?) dependency of PyTorch, it'd be nice to solicit feedbacks from PyTorch core devs as well?

Thank you for the suggestion - that's a great point!

**Comment by leofang** [comment]
Thank you, @jakirkham and @gmarkall, for your detailed replies! I still have a few questions on the API design and the future asynchronous extension, but they are irrelevant in the cupy scope and I will move the discussion to your issue tracker.

**Comment by kmaehashi** [comment]
Closing as NBEP 7 has been finalized.
Feel free to leave a comment so that we can reopen it.
