### ISSUE TITLE
cupy.take() does not function correctly when indices are unsigned integers or negative

### ISSUE THREAD

**Issue by coderforlife** [cupy/cupy#3017]
```
CuPy Version          : 7.1.1
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2506
NCCL Runtime Version  : 2506
```

**Code to reproduce**
```
a = cp.ones(256)
indices = cp.array([150], dtype=cp.uint8)
a.take(indices)
```
This should result in an array with the value `1` in it (since the original `a` was only ones) however this gets `0` or other random values instead. Seems to be treated it as the value -106 instead of 150 allowing one to read data outside of the array (also note that apparently negative indices are also allowed and also grab garbage data).

**Comment by takagi** [comment]
Thanks for the reporting. I reproduced the issue and will look into its detail.

**Comment by takagi** [comment]
I’ve found that the issue is not because the index to take is interpreted as `int8` but the type of `index_range` in the take kernel is specified to `uint8` as well as that of `indeces`, which can not represent 256 that is the size of `a` and, causes taking a value somewhere unexpected.

https://github.com/cupy/cupy/blob/bb3205ceb85996328e0c95a7bec385430b38c454/cupy/core/_routines_indexing.pyx#L366-L368

If we make the size of `a` 255 instead of 256, the following code works:

```Python
>>> a = cp.ones(255)
>>> indices = cp.array([150], dtype=cp.uint8)
>>> a.take(indices)
array([1.])
```
