### ISSUE TITLE
implementing array_equal() for CuPy

### ISSUE THREAD

**Issue by portfoliocreator** [cupy/cupy#3125]
I was trying to implement array_equal() for Cupy and was thinking along these lines

```py
def array_equal(a1, a2):
    try:
        a1, a2 = cupy.asarray(a1), cupy.asarray(a2)
    except Exception:
        return False
    if a1.shape != a2.shape:
        return False
    return bool(cupy.asarray(a1 == a2).all())
```

Should I move forward with this ? I would be grateful if someone could guide me.

**Comment by emcastillo** [comment]
Hello, thanks for being interested in contributing to CuPy!.

1st is that `asarray` checks are not needed, since cupy functions accepts only cupy arrays. https://docs-cupy.chainer.org/en/stable/reference/difference.html#universal-functions-only-work-with-cupy-array-or-scalar

2nd is that this function currently synchronizes the device when you do `return bool(...)`
just doing a `return (a1==a2).all()` should be fine.

For sending a PR you will need to add a docstring to the function and also add tests for the external behavior.

**Comment by rushabh-v** [comment]
are you interested in opening a PR? @portfoliocreator 
Otherwise, I would be fine doing it. :D

**Comment by portfoliocreator** [comment]
@rushabh-v Yes , sure go ahead.
