### ISSUE TITLE
Drop cuDNN support in v8

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3303]
CuPy has been providing support for cuDNN since the initial release. It has been developed mainly for Chainer. However, as the last major version series of Chainer (v7.x) does not support CuPy v8+, there is no explicit use-case for cuDNN module in CuPy.

By dropping support for cuDNN, we can:

* Reduce maintenance cost to keep up with the latest cuDNN.
* Reduce wheel package footprint (200MB+) -- Reduced download time for users. As for the maintainer, the preparation of wheels for each release will also become easier.

This is still under discussion and not finalized decision. If you have any concerns please leave a comment in this issue.

**Comment by ryansynk** [comment]
Currently working on a project and we're planning on using CuPy, but my use case would require CuDNN support.

**Comment by miguelusque** [comment]
I’d suggest to have two different wheels, one with cuDNN support, and another without it.

In terms of usage, AFAIK some people still use cuDNN to train their models, so they might benefit of CuPy + cuDNN integration.

**Comment by kmaehashi** [comment]
Thanks for the feedback!

> Currently working on a project and we're planning on using CuPy, but my use case would require CuDNN support.

@ryansynk  Could you briefly describe the project? Do you use `cupy.cudnn` or `cupy.cuda.cudnn`? Do you think it is acceptable if we drop the cuDNN library from wheels while keeping the cuDNN binding code (so users who want to use cuDNN can build CuPy from source to use it)?

> In terms of usage, AFAIK some people still use cuDNN to train their models, so they might benefit of CuPy + cuDNN integration.

@miguelusque I'm curious about that use-case. Do they use CuPy without DL frameworks for training?

**Comment by honnibal** [comment]
Hi @kmaehashi ,

Thanks again for your work on cupy. I understand that your team may need to reassess your priorities after the decisions concerning Chainer. The spaCy community has benefited greatly from all your work on cupy, and I've been planning to make more use of the cuDNN bindings. I hope a solution can be found that allows the bindings to stay within cupy, but I understand the maintenance costs.

The cuDNN routines are an important resource for ML, and so it's very beneficial to the Python community to have a generic access to them, with an API that stays close to the underlying library. It's also very beneficial to have the cuDNN bindings integrated with the array types, so that you can pass in cupy arrays. All of the work you've done on this is really valuable for the Python community.

If the cuDNN bindings are dropped from cupy, alternative solutions for a library like spaCy will all be quite difficult. We would need to build the bindings against cupy, which could be possible if you provide the .pxd files. It won't be very easy though.

I've been talking to some folks from nvidia and explaining how important cupy is for the Python community. I'm hoping that a solution can be found where they get more involved in the maintenance, so that the development is more sustainable.

**Comment by kmaehashi** [comment]
Thank you all for the feedback! We also received several feedbacks privately regarding cuDNN support. We now recognized that many people want to use cuDNN via CuPy, so we decided not to drop support in v8.

**Comment by honnibal** [comment]
Thanks, that's great news!

I don't want to overpromise but I hope I can contribute some documentation for it.

**Comment by miguelusque** [comment]
Thank you! This is great news!

**Comment by leofang** [comment]
Update: CuPy plans to remove cuDNN support, see https://github.com/cupy/cupy/issues/8215#issuecomment-1989785373.
