### ISSUE TITLE
Build CuPy from source with C++ 14

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3346]
CUB 1.9.9 and 1.9.10 require c++14. Is it possible to build CuPy from source and pass c++14?

**Comment by leofang** [comment]
> CUB 1.9.9 and 1.9.10 require c++14. 

C++11 is not yet dropped, only deprecated: https://github.com/thrust/cub/pull/21. I think this deprecation will be done in both Thrust and CUB that come with CUDA 11. But, given that some Linux distros still ship old compilers (say gcc <=4.8.5; this is also part of the reason that [blocks CuPy from making CUB built-in](https://github.com/chainer/chainer-test/pull/564)) and that a lot users will still be on CUDA<11 even it's out, dropping them might be a little too soon. 

Just FYI, #2584 was a plan to bundle CUB with CuPy so that the CUB support works for pre-CUDA 11 users. Since a git submodule is used, updating to newer CUB is easy.

> Is it possible to build CuPy from source and pass c++14?

If you build from source, you can change this line: https://github.com/cupy/cupy/blob/e6474838a922b7869fb56380c8b9421702da1b26/cupy_setup_build.py#L850
It'll affect both modules `cupy.cuda.thrust` and `cupy.cuda.cub` (the only two modules in CuPy that require `nvcc`).

**Comment by mnicely** [comment]
@leofang You are correct! Sorry for the misstatement. Thanks!

**Comment by jakirkham** [comment]
Should we make this change in conda-forge package @leofang? The compilers there already support C++17.

**Comment by leofang** [comment]
I don't think there'd be any problem. But unless 1. CUDA 11 is out, or 2. CUB support is to be built, does it matter which C++ standard we pick?

**Comment by jakirkham** [comment]
It's worth noting I don't write that much C++ these days. That said, here's a nice [blogpost on C++17 changes]( https://www.perforce.com/blog/qac/should-i-adopt-cpp17 ). There can be performance improvements in newer standards (C++17 has some [copy elision]( https://en.cppreference.com/w/cpp/language/copy_elision ) improvements). Some standards make behavioral changes (though I think C++11 is more notable for this). Though the main reason to use a newer standard would be features (not sure how much that matters to us here).

Though to the conda-forge point, it would ensure are packages are being built more closely to the [default conda-forge compiler flags]( https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/eac83f495f22488f449ff6c564e000105f9c8346/recipe/conda_build_config.yaml#L30 ), which include C++17 support.

**Comment by leofang** [comment]
My impression is that currently (pre-CUDA 11) both Thrust and CUB do not support C++17. I could  be wrong, though. C++14 (if we're gonna do it) seems safer.
