### ISSUE TITLE
Copy Memory-mapped file into CuPy array

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3431]
Would it be possible to copy the output of `mmap.mmap` into a CuPy array of type void?
I want to read in a binary file into the GPU.

What I can do now:
1. I can use the examples [here](https://github.com/rapidsai/cusignal/issues/117) and then use `cp.asarray`.

That's not optimal, so I'l like to read the binary straight into GPU memory.
2. I'm able to do this with C++ [here](https://github.com/rapidsai/cusignal/pull/122). But will require Cython binding and memory management handling for the rest of our CuPy functions.

Would it possible to implement something like #2 with CuPy.

Example 1. Copy data from file to `mm` as raw data. Then copy to CuPy array and cast?
```python
with open(filename, "r+") as f:
    mm = mmap.mmap(
        f.fileno(),
        num_bytes,
        flags=mmap.MAP_PRIVATE,
        prot=mmap.PROT_READ,
    )

d_binary = cp.asarray(mm, dtype=cp.complex64)
```

Example 2. Copy data from file to `mm` as raw data. Then copy binary data to CuPy array? 
Once on the GPU, I can launch a kernel to reinterpret the data.
```python
with open(filename, "r+") as f:
    mm = mmap.mmap(
        f.fileno(),
        num_bytes,
        flags=mmap.MAP_PRIVATE,
        prot=mmap.PROT_READ,
    )

d_binary = cp.asarray(mm)
```

**Comment by leofang** [comment]
Just curious, did the two examples only differ in the extra `dtype` argument? And you assumed that `mm` here is wrapped in a numpy array?

Not sure if this helps or not. You could just copy the whole contiguous chunk using `MemoryPointer`:
```python
from cupy.cuda import memory

size = mm.size()
mmap_ptr = ...  # get mmap pointer, say using from_buffer or create a numpy array first
gpu_ptr = memory.alloc(size)  # a MemoryPointer instance
gpu_ptr.copy_from(mmap_ptr, size)  # there's also an async version
```
and if you want you could create a CuPy array using `cp.ndarray(..., memptr=gpu_ptr, ...)`.

My ongoing PR #3244 will allow `RawKernel`s to accept `MemoryPointer`s as a valid launch input. If you have a strong need I can make a separate PR (because that one may take a while to get a green light).

**Comment by leofang** [comment]
One more thing:
> 2. I'm able to do this with C++ [here](https://github.com/rapidsai/cusignal/pull/122). But will require Cython binding and memory management handling for the rest of our CuPy functions.

Not sure what you meant with the binding and memory handling. But if your data already lives on GPU and you know its pointer address (say `ptr`), you can make it a `MemoryPointer`:
https://github.com/cupy/cupy/blob/4916d9481d189246334fcc835861d5ac95c756b8/cupy/core/raw.pyx#L415-L418

**Comment by jakirkham** [comment]
One note here is `mmap.mmap` objects support [the Python Buffer Protocol]( https://docs.python.org/3/c-api/buffer.html ), which `numpy.asarray` can use to view the underlying data zero-copy. So it's possible to view the `mmap.mmap` object as a NumPy array and then copy that to device with `cupy.asarray` (as one would do with any other NumPy array).

```python
import mmap
import numpy
import cupy

m = mmap.mmap(-1, 5)
cupy.asarray(numpy.asarray(m))
```

**Comment by leofang** [comment]
That's exactly right. Zero-copy is the most common reason to use mmap. Another way to wrap a mmap with a NumPy array is to do this:
```python
mm = mmap.mmap(...)
arr = np.ndarray(..., buffer=mm, ...)
```

**Comment by mnicely** [comment]
Thanks for the help! I was able to get the following working well!

```python
with open(file, "r+") as f:
        mm = mmap(f.fileno(), 0, flags=MAP_PRIVATE, prot=PROT_READ,)
out = cp.asarray(mm)
```

**Comment by jakirkham** [comment]
Would recommended moving the `out` definition into the `with` block. Otherwise looks good :)

**Comment by leofang** [comment]
I was surprised so looked into why. Turns out for unrecognized objects CuPy internally wraps it in a NumPy array first (I think for the case of mmap it is still a zero-copy op), and then copy to pinned memory for faster transfer to device:
https://github.com/cupy/cupy/blob/18b8fc8b1f10789251f26b5895f823378ad04bf7/cupy/core/core.pyx#L2116-L2141
I am curious if we can combine pinned memory with mmap to further speed up this...?

**Comment by mnicely** [comment]
@leofang I wonder if that’s what’s going on at the beginning of the read under the cuSignal NVTX marker. If you checkout my PR 122, you see a Nsight Systems screenshot. We are all for speed-ups! Now that I have skeleton code, we’ll be adding more formats to parse. 😁

**Comment by leofang** [comment]
Yeah you meant cudaHostMalloc, right?

This mmap+pinned memory thing reminds me #2481 and [this SO post](https://stackoverflow.com/a/57762413) by Robert Crovella. May be useful to you?

**Comment by mnicely** [comment]
No, I'm referring to time segment +715ms -> +748ms. I've attached a zoomed screenshot of Systems, with Events View of that filtered selection.

It looks like this code (with @jakirkham suggestion) (removed nvtx markers)
```python
try:
    with open(file, "r+") as f:
        mm = mmap(f.fileno(), 0, flags=MAP_PRIVATE, prot=PROT_READ,)
        out = cp.asarray(mm)
except KeyError:  # FIX
    raise NotImplementedError

if autosync is True:
    cp_stream.synchronize()

return out
```
is doing the following CUDA API calls 
```bash
cudaMalloc
cudaEventQuery
cudaEventDestroy
cudaMemcpyAsync
cudaEventCreateWithFlags
cudaEventRecord
cudaEventQuery
cudaStreamSynchronize
```
With a larger gap between **cudaEventDestroy** and **cudaMemcpyAsync**, ~30ms.

I looks like the `mmap` only takes 10.5us, while the `asarray` takes 30ms.
![sigmf_reader_nsys_zoomed](https://user-images.githubusercontent.com/50021634/84555663-fcfdb980-aceb-11ea-93ef-7f9e4252269e.png)

![sigmf_reader_nsys_zoomed_nvtx](https://user-images.githubusercontent.com/50021634/84555676-16066a80-acec-11ea-98e1-8a90d178b79c.png)

**Comment by mnicely** [comment]
After reading the comments again, this might be what's going on. https://github.com/cupy/cupy/issues/3431#issuecomment-643479935

**Comment by takagi** [comment]
As for https://github.com/cupy/cupy/issues/3431#issuecomment-643479935, using `cudaHostRegister` may eliminate the extra copy from mmapped region to the pined one.

**Comment by leofang** [comment]
Interesting thought. That, perhaps together with https://github.com/cupy/cupy/issues/3431#issuecomment-642918444, might reduce the internal overhead.

I'd hope that CUDA provides an API that returns a file descriptor for pinned memory. Then we can revert this process: instead of mmap -> `cudaHostRegister`, we do `cudaHostMalloc` -> get the corresponding file descriptor -> mmap, which seems more natural. Too bad this utility doesn't exist 😂 We do this frequently with POSIX shared memory and it's quite handy.

**Comment by leofang** [comment]
> This mmap+pinned memory thing reminds me #2481 and [this SO post](https://stackoverflow.com/a/57762413) by Robert Crovella. May be useful to you?

This now becomes a library called SpeedTorch: https://github.com/Santosh-Gupta/SpeedTorch.

**Comment by Santosh-Gupta** [comment]
> > This mmap+pinned memory thing reminds me #2481 and [this SO post](https://stackoverflow.com/a/57762413) by Robert Crovella. May be useful to you?
> 
> This now becomes a library called SpeedTorch: https://github.com/Santosh-Gupta/SpeedTorch.
> 
> cc: @Santosh-Gupta in case he has better insight 🙂

I basically just used that single technique and make a pytorch library around it. I still very unfamiliar with Cuda. Maybe we can reach out to Robert Crovella directly.

**Comment by jakirkham** [comment]
It might be worth exploring different [`mmap`]( https://www.man7.org/linux/man-pages/man2/mmap.2.html ) flags as well, @mnicely.

In particular there are some `MAP_HUGE*` flags, which use larger page sizes, which would allow the GPU to copy more data over to device at once and perform fewer copies for the same total amount of data. [NumPy does something similar]( https://github.com/numpy/numpy/blob/da1621637b7c59c155ec29466fb5f810ebd902ac/numpy/__init__.py#L334-L353 ) for memory it allocates, which winds up being pretty useful.

Another interesting option is `MAP_LOCKED`. This would allow one to page lock all of the memory, which effectively is like making the page size the entire block of memory and not allowing the system to unpage it. Though the man page suggests using [`mlock`]( https://www.man7.org/linux/man-pages/man2/mlock.2.html ) if one really wants to avoid page faults  (which we would). I don't see a Python implementation of this, but it should be accessible through [`ctypes`]( https://docs.python.org/3/library/ctypes.html ) or Cython.

Would pick either hugepages or page locking. I don't think these would make sense together (though anyone please feel free to correct me if I'm wrong here).

Also make sure to unmap files once done with them (by using Python context managers or explicitly calling `.close()`). Otherwise large amounts of page cache will remain occupied and degrade overall program and/or system performance.

Python may not include all of these flags. So it is possible one would need to look in the corresponding Linux header and figure out the values for these flags. Don't forget to bitwise-or flags since these are just being passed straight to C, which would interpret them that way.

**Comment by mnicely** [comment]
@jakirkham Thanks for the tips! I tried `MAP_HUGE*` but it had issues passing CI. I will revisit it when I have more time, but I believe I will need to add logic for the scenarios where the flag is not an option on a particular system.
