### ISSUE TITLE
Reorganize CUB environment variables

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3445]
Currently there're 4 CUB-related environment variables.

* CUB_PATH: used at build time to build cupy.cuda.cub
* CUPY_CUB_PATH: used at runtime to build  reduction kernel (#3244)
* CUPY_CUB_BLOCK_REDUCTION_DISABLED (default: 1): Set to 0 to enable performance boost in reduction kernel (#3244)
* CUB_DISABLED (default: 1): Set to 0 to enable CUB in various computations

We think it is better to disable CUB by default, even in CUDA 11, as users expect reproducibility (deterministic behavior). Instead, we need to provide a simple "opt-in" method to enable CUB for users needing a performance boost.

This issue proposes the followings:
* Remove CUB_PATH and CUPY_CUB_PATH (always use bundled CUB #2584 or CUDA 11 built-CUB, as user-provided CUB headers are unlikely to be used (considering we haven't requested to implement CUPY_THRUST_PATH).
  * In CUDA 11, use CUB included in CUDA runtime. If CUB headers are unavailable in system (e.g., maybe in "runtime" docker container; need to check after CUDA 11 is finally released), use CUB bundled in CuPy.
  * In CUDA 10 or earlier, always use CUB bundled in CuPy.
* Merge `CUPY_CUB_BLOCK_REDUCTION_DISABLED` and `CUB_DISABLED` into one environment variable `CUPY_BACKENDS="cub,cutensor"` (default: "", i.e., cub/cutensor disabled by default). Users can specify backends in the referred order, separated by a comma. Boolean flags (`cupy.core.cub_block_reduction_enabled` and `cupy.cuda.cub_enabled`) are removed for consistency.
* For testing and debugging purposes, provide the following undocumented APIs:
```
cupy.core.set_routine_backends(['cub', 'cutensor'])
cupy.core.set_reduction_backends(['cub', 'cutensor'])
```

(edit 2020-06-25: updated based on the latest discussion)

cc/ @leofang @anaruse

**Comment by leofang** [comment]
Thanks for organizing the logics, @kmaehashi!

> * Remove CUB_PATH and CUPY_CUB_PATH (always use bundled CUB #2584 or CUDA 11 built-CUB, as user-provided CUB headers are unlikely to be used (considering we haven't requested to implement CUPY_THRUST_PATH).

As I explained recently in #2584 and in https://github.com/cupy/cupy/pull/3244#issuecomment-644269815, we prefer to keep `CUPY_CUB_PATH` (and use it in both build time for `cupy.cuda.cub` and in runtime for using `cupy.core.cub_reduction`) because on conda-forge we can make `cupy` depend on `cub` (which is version-locked to `thrust` and vice versa). This was @jakirkham's proposal (https://github.com/conda-forge/cupy-feedstock/issues/60).

In any case, `CUB_PATH` is better to be removed (I marked it deprecated in #2584). Name collision is very unlikely to happen, but not impossible... 

> * Merge `CUPY_CUB_BLOCK_REDUCTION_DISABLED` and `CUB_DISABLED` into one environment variable `CUPY_CUB_ENABLED` (default: 0, set to 1 to opt-in).

I don't have objection on combining them 👍 `CUPY_CUB_BLOCK_REDUCTION_DISABLED` was more a workaround/unresolved leftover from #3244, which I dislike. 

But, I have two comments (probably not a big deal):
1. if you are setting default to 0, why not just keep `CUB_DISABLED` as is? (Double negative is annoying, I admit...)
2. Combining them will lose the flexibility to toggle them on/off separately using env vars, and runtime toggles as listed in your table would be the only solution.

> * Provide `cupy.core.cub_reduction.enable` flag (default: True) to provide an option to turn-off CUB in reduction feature. (note: `cupy.core.cub_reduction` refactoring in progress by @asi1024 )

Sounds good. So this will replace `cupy.core.cub_block_reduction_enabled` from #3244, right?

By the way, I think the last element in the 3rd row of your table is wrong. CUB (reduction) should be **Enabled** when `cupy.core.cub_reduction.enable=True`.

**Comment by emcastillo** [comment]
> As I explained recently in #2584 and in #3244 (comment), we prefer to keep CUPY_CUB_PATH (and use it in both build time for cupy.cuda.cub and in runtime for using cupy.core.cub_reduction) because on conda-forge we can make cupy depend on cub (which is version-locked to thrust and vice versa). This was @jakirkham's proposal (conda-forge/cupy-feedstock#60).

Won't we be building cupy with the cub bundled in the git submodule or the cuda11 one?

**Comment by leofang** [comment]
> Won't we be building cupy with the cub bundled in the git submodule or the cuda11 one?

First, I thought about it today, and I feel once we bundle it, we won't be able to choose the CUDA 11 one without explicitly overwriting (via `CUPY_CUDA_PATH`).

Next, I guess @jakirkham was having in mind -- I may be very wrong -- that we as package maintainers are free to choose newer CUB should one be available, not bound by anyone's release cycle. 😂

But, I do wanna point out that it's best to stick to CuPy's choice of CUB, because it gets tested by the CIs here. We have experienced multiple issues not having CI get our back...

**Comment by kmaehashi** [comment]
> if you are setting default to 0, why not just keep CUB_DISABLED as is? (Double negative is annoying, I admit...)

It's because we thought it's better to avoid double-negative and follow "set 1 to enable" convention like as in other environment variables.
https://docs-cupy.chainer.org/en/latest/reference/environment.html

> Sounds good. So this will replace cupy.core.cub_block_reduction_enabled from #3244, right?

Yes. (sorry, I updated the text just before you post the comment)

> By the way, I think the last element in the 3rd row of your table is wrong. CUB (reduction) should be Enabled when cupy.core.cub_reduction.enable=True.

This is intentional (CUPY_CUB_ENABLED is the master control of CUB features in CuPy).

**Comment by kmaehashi** [comment]
> But, I do wanna point out that it's best to stick to CuPy's choice of CUB, because it gets tested by the CIs here. We have experienced multiple issues not having CI get our back...

Regarding `CUPY_CUDA_PATH`, I think it's better to avoid mixing various versions of CUB (use `cub` conda package for reductions, use CuPy-bundled CUB for others).
* It is difficult to guarantee future CUB + CuPy to work, and difficult to reproduce an error reported by users
* I think CUB is relatively stable and users are unlikely to need non-bundled versions

**Comment by leofang** [comment]
> > By the way, I think the last element in the 3rd row of your table is wrong. CUB (reduction) should be Enabled when cupy.core.cub_reduction.enable=True.
> 
> This is intentional (CUPY_CUB_ENABLED is the master control of CUB features in CuPy).

Ah, OK, but it'd be nice to able to turn off global/general CUB and turn on `cupy.core.cub_reduction`. It's useful at least for debugging and benchmarking. Could you think of some way to do this (could be undocumented 😇)?

**Comment by leofang** [comment]
> Regarding `CUPY_CUDA_PATH`, I think it's better to avoid mixing various versions of CUB (use `cub` conda package for reductions, use CuPy-bundled CUB for others) in a single release.

I agree. So, if on conda-forge we are determined to make `cupy` depend on `cub` (overwriting the bundle), we will need to set `CUPY_CUB_PATH` to conda's include dir in the activation script to ensure the CUB seen at runtime is identical to that at build time. This was the original intention when I did this:
https://github.com/cupy/cupy/blob/311390a7923cf7fb06ad5527c7c40f3b0a968f88/cupy/_environment.py#L77-L78

**Comment by leofang** [comment]
> > Regarding `CUPY_CUDA_PATH`, I think it's better to avoid mixing various versions of CUB (use `cub` conda package for reductions, use CuPy-bundled CUB for others) in a single release.
> 
> I agree. So, if on conda-forge we are determined to make `cupy` depend on `cub` (overwriting the bundle), we will need to set `CUPY_CUB_PATH` to conda's include dir in the activation script to ensure the CUB seen at runtime is identical to that at build time. This was the original intention when I did this:
> 
> https://github.com/cupy/cupy/blob/311390a7923cf7fb06ad5527c7c40f3b0a968f88/cupy/_environment.py#L77-L78

Not saying we are bound to do this, just providing a solution.

**Comment by leofang** [comment]
How about `cupy.cuda.cub_enabled`? Is it controlled by `CUPY_CUB_ENABLED`?

**Comment by emcastillo** [comment]
> (overwriting the bundle)

Why would you want to overwrite the bundle? (I am asking because I can't figure out such situation 😥)

**Comment by kmaehashi** [comment]
We discussed and come up with this solution:

(1) Provide documented APIs to specify the order of preferred backends. Both are empty by default (i.e., fallback to use naive cupy implementation).

```
CUPY_ROUTINE_BACKENDS="cub,cutensor"
CUPY_REDUCTION_BACKENDS="cub,cutensor"
```

(2) Provide undocumented APIs for debugging and benchmarking purposes:

```
cupy.core.set_routine_backends(['cub', 'cutensor'])
cupy.core.set_reduction_backends(['cub', 'cutensor'])
```

**Comment by leofang** [comment]
> > (overwriting the bundle)
> 
> Why would you want to overwrite the bundle? (I am asking because I can't figure out such situation 😥)

@emcastillo Because [we can then use newer CUB](https://github.com/cupy/cupy/issues/3445#issuecomment-645163811) from conda-forge, see [all available versions here](https://anaconda.org/conda-forge/cub/files). Moreover, it allows us to simplify the package recipe as follows (@jakirkham correct me if I'm wrong!):
```jinja
requirements:
  build:
    - (...)

  host:
    - (...)
    - cub ==1.9  # this also pulls down thrust
    run_exports:
      strong:
        - cub

  run:
    - (...)
    # dependency on exactly the same version of cub/thrust is inherited via run_exports
```
The effect is more or less the same as what would be achieved with `conda install -c conda-forge cupy cub==1.9 ...`, but with all the dependency requirements resolved and taken care by conda.

> We discussed and come up with this solution:

Thank you, @kmaehashi! So am I understanding it correctly on the final decision for runtime APIs?
- Public: `cupy.core.cub_reduction.enable` & `cupy.cuda.cub_enable`
- Private/undocumented: `cupy.core.set_*_backends()`

**Comment by emcastillo** [comment]
> @emcastillo Because we can then use newer CUB from conda-forge, see all available versions here. Moreover, it allows us to simplify the package recipe as follows (@jakirkham correct me if I'm wrong!):

I think we should stick to the bundled cub when distributing binaries because it is the main one tested and make user configurations deterministic across package systems. Changing packages versions depending on the environment is most likely going to give us headaches later on.

If the user wants to try a different cub version then he/she can update the submodule folder.

**Comment by leofang** [comment]
> we should stick to the bundled cub when distributing binaries because it is the main one tested
>
> If the user wants to try a different cub version then he/she can update the submodule folder.

Makes sense to me. This echos what I said earlier too.

Just need a final confirmation on this part:

> So am I understanding it correctly on the final decision for runtime APIs?
> 
> * Public: `cupy.core.cub_reduction.enable` & `cupy.cuda.cub_enable`
> * Private/undocumented: `cupy.core.set_*_backends()`

**Comment by leofang** [comment]
Another thing is what do you plan for CUDA 11? Do you wanna use CuPu's CUB or CUDA's? I guess it depends if you have a separate CI to test CUDA 11 or not...

**Comment by kmaehashi** [comment]
> Thank you, @kmaehashi! So am I understanding it correctly on the final decision for runtime APIs?

I'm thinking of `cupy.core.cub_reduction.enable` & `cupy.cuda.cub_enable` to be removed, as they're confusing after  "preferred order of backends" concept is introduced.

After discussing with @asi1024, we're now going to provide documented public interface `CUPY_BACKENDS="cub,cutensor"` env var, which controls the default preferred order of backends for both reduction and routines. For testing and debugging purposes, you can use undocumented `cupy.core.set_*_backends()`.

**Comment by kmaehashi** [comment]
> Another thing is what do you plan for CUDA 11? Do you wanna use CuPy's CUB or CUDA's?

My idea is:
1. In CUDA 11, use CUB included in CUDA runtime. If CUB headers are unavailable in system (e.g., maybe in "runtime" docker container? I'm not sure as CUDA 11.0 is still RC...), use CUB bundled in CuPy.
2. In CUDA 10 or earlier, always use CUB bundled in CuPy. No external `CUB_PATH`.

@asi1024 @emcastillo  How do you think?

> I guess it depends if you have a separate CI to test CUDA 11 or not...

I'm now preparing CI for CUDA 11.
The first cupy-cuda110 release would be in the next month.

**Comment by emcastillo** [comment]
I agree with @kmaehashi proposal

**Comment by leofang** [comment]
Sounds good. I'll resolve the conflict in #2584 based on this discussion.

**Comment by leofang** [comment]
@kmaehashi Could you update the issue summary to reflect everything discussed above? It'd be easier to refer to. Thanks!

**Comment by kmaehashi** [comment]
Updated.

**Comment by leofang** [comment]
`CUPY_CUB_PATH` currently exists in a few places: 
https://github.com/cupy/cupy/search?q=CUPY_CUB_PATH&unscoped_q=CUPY_CUB_PATH
I will send a PR to remove them.

**Comment by leofang** [comment]
Thank you, @kmaehashi! Glad to see everything works out! 💪
