### ISSUE TITLE
empty_like should match device?

### ISSUE THREAD

**Issue by carterbox** [cupy/cupy#3457]
I observed some unexpected behavior regarding `empty_like` and other `_like` functions. Specifically, the allocated arrays do not match the device of the template array; they are allocated on the default device instead. Since these function are supposed to return an array "like" the template array, shouldn't the new array have the same device as the template array?

```python
import cupy as cp

with cp.cuda.Device(1):
        a = cp.random.rand(10)
print(a.device, 'should be 1')

# Allowed without context because only one host.
ah = cp.asnumpy(a)

# Should be 1 because arrays like 'a' are on device 1.
a_like = cp.empty_like(a)
print(a_like.device, 'should be 1')

# Should be 0 because default device is zero.
c = cp.asarray(ah)
print(c.device, 'should be 0')

```
```
<CUDA Device 1> should be 1
<CUDA Device 0> should be 1
<CUDA Device 0> should be 0
```

Conditions
  - CuPy 7.5.0
  - RHEL x64
  - CUDA 10.2

**Comment by leofang** [comment]
I think this behavior is expected (for me) as it's outside the context of Device 1. I don't think there is any requirement from NumPy's `*_like()` functions that they must live in the same (whatever) context, and I would prefer to remain the status quo, as CuPy's `Device` API has been there longer than those newcomers...

**Comment by leofang** [comment]
Another reason for not matching device: I think it would break CUDA's semantics. Consider this snippet (which works fine currently):
```python
import cupy as cp

with cp.cuda.Device(1):
    a = cp.random.random(10)

b = cp.empty_like(a)  # suppose this lives on device 1...
c = cp.exp(b)         # ...then this would break
```
With your proposal, this snippet would (and should) break. The reason is under the hood the `Device` API follows the same semantics as CUDA's `cudaGetDevice`/`cudaSetDevice`, so outside the `Device(1)` context subsequent calls would think we're on device 0, allocate memory (for `c`) on device 0, and launch a kernel on device 0 with a device-0 pointer (`c`) and, based on what you suggested, a device-1 pointer (`b`).

**Comment by carterbox** [comment]
Makes sense to follow CUDA's semantics. Thanks for the explanation, @leofang! :smile:

**Comment by leofang** [comment]
Glad I'm still making sense (despite lack of sleep...) 😁
