### ISSUE TITLE
Support batched SVD (`cupy.linalg.svd`)

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3470]
https://github.com/cupy/cupy/pull/2337#issuecomment-630577091
> It is supposed that now batched cupy.cusolver.gesvdj that uses cusolverDn<t>gesvdjBatched is merged in #3247 and remaining is to fix cupy.linalg.svd to support batched svd using cupy.cusolver layer.

**Comment by leofang** [comment]
Python Array API will require this capability: https://github.com/data-apis/array-api/pull/114

**Comment by leofang** [comment]
Looks like #3247 provides the needed support, I wonder why it wasn't included in `cupy.linalg.svd`? @toslunar Do you remember?

**Comment by toslunar** [comment]
I'd like to support the batched case, and now I suppose it requires a warning in the docstring.

I was uncertain if it's acceptable to use different algorithms depending on shapes.  We will see two types of the difference:

- **sign** (because of the arbitrariness of SVD): It may damage careless users.  For example, recomputing SVDs (for debugging or for memory efficiency) will not always be a good idea.
- **precision**: It shouldn't be a big deal.  Users who want to choose a suitable algorithm for their input can call `cupy.cusolver` functions.

**Comment by leofang** [comment]
Thanks for reply, @toslunar. I am thinking to call `gesvdjBatched` in `cupy.linalg.svd` when the input has `ndim>=3`, and I am a bit confused from what you said: it does not seem to be possible to set which algorithm to use in `cusolverDn<t>gesvdjBatched()`. Do I miss something?

**Comment by toslunar** [comment]
Sorry.  I meant `gesvd` and `gesvdj` are different in algorithm.  `cupy.linalg.svd` uses `cusolverDn<t>gesvd()` for a 2-dim input, but `cusolverDn<t>gesvdBatched()` does not exist.

**Comment by leofang** [comment]
Ah OK I understand now. I think adding a warning in the docstring is sufficient to unblock things. 
> I was uncertain if it's acceptable to use different algorithms depending on shapes.

I think it's acceptable as it's common to change the underlying algorithm for different kinds of inputs, in this case the shape. Would you like me to send a PR or you'd prefer to do this yourself @toslunar? 🙂
