### ISSUE TITLE
Difference from SciPy about sparse min/max `sum_duplicates` parameter

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#3535]
I'm not sure its background, but currently, sparse min/max have `sum_duplicates` parameter and its default value is `False`. However, their SciPy counterparts don't have the parameter and always sum duplicate entries as `sum_duplicates=True`.

It would be better to change its default value to `False`.

**Comment by kmaehashi** [comment]
This features was added in #2711

**Comment by dloney** [comment]
I would say toggling the default behavior from False to True to be consistent with scipy would be good. The reason I introduced the flag is as a performance enhancement to skip the sum_duplicates operation if the user knows their matrix is canonical. Changing the default flag will make it conform with the default scipy behavior.

For #3583, there's an open pull request on scipy that will implement the explicit nonzero features. I wouldn't remove the functionality from cupy for the sake of standardizing to scipy since it's a useful feature when explicit zeros are included in the sparse matrix. The default behavior for the non_zero flag is the same as standard scipy. The scipy pull request uses the keyword "explicit" rather than "nonzero" which might be a good change to make.
