### ISSUE TITLE
Improve printing compiler log to stream

### ISSUE THREAD

**Issue by emcastillo** [cupy/cupy#3554]
Follows #3485 

This PR introduced a mechanism to use a user opened stream for saving compiler warnings when compiling RawKernels.

However, the stream is passed on the `__init__` method but is not employed until the code is compiled, which can be pretty late in the execution.

We should discuss a way to effectively manage streams in this situation.

**Comment by asi1024** [comment]
There are two kinds of solutions in my mind.

1. Buffering the warning messages in `RawKenrel` object and provide an interface to get the message (as we discussed offline).
In this solution, we should leave the `log_stream` argument in `__init__` because we don't want to call `nvrtc.getProgramLog` if not needed.
2. Providing an interface to compile the kernel explicitly and move the feature to the new interface.
We can remove `log_stream` argument from `__init__` in this way.

Both fixes change the current behavior, so I want to resolve this issue until `v8.0.0rc1` is released in any case.

**Comment by emcastillo** [comment]
I like 2 more, having an interface to explicitly compile a kernel might have other nice use cases. We could do this with ElementWise and ReductionKernels as well.

it is good to avoid some of the currently present magic.

**Comment by leofang** [comment]
cc: @mnicely

**Comment by leofang** [comment]
> I like 2 more, having an interface to explicitly compile a kernel might have other nice use cases. 

My very first PR to CuPy (#1889) implemented `RawKernel.compile()`. I take this as a compliment for my foresight? 😂
