### ISSUE TITLE
`cupy.fft.irfft` is slow

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#3556]
`cupy.fft.irfft` is extremely slow and causes unexpected device synchronization.
```
fft     :    CPU:  511.504 us   +/-182.837 (min:  466.546 / max: 6098.848) us     GPU-0:  914.825 us   +/-181.750 (min:  868.352 / max: 6491.872) us
ifft    :    CPU:  516.756 us   +/-89.689 (min:  499.988 / max: 3025.299) us     GPU-0:  993.364 us   +/-83.566 (min:  970.336 / max: 3351.712) us
rfft    :    CPU:  473.139 us   +/-12.516 (min:  462.383 / max:  624.113) us     GPU-0:  711.520 us   +/-12.456 (min:  699.104 / max:  857.184) us
irfft   :    CPU:483281.932 us   +/-5010.430 (min:479695.227 / max:490367.569) us     GPU-0:483321.136 us   +/-5021.194 (min:479726.959 / max:490421.997) us
```

Reproducer:
```py
import cupy
import cupyx


a = cupy.random.rand(5000000).astype('f')

funcs = [
    cupy.fft.fft,
    cupy.fft.ifft,
    cupy.fft.rfft,
    cupy.fft.irfft,
]

for f in funcs:
    perf = cupyx.time.repeat(f, (a,), n_warmup=5, max_duration=1)
    print(perf)
```
cc: @leofang

**Comment by emcastillo** [comment]
Sync is caused by
https://github.com/cupy/cupy/blob/master/cupy/fft/fft.py#L103

Only for irfft

**Comment by emcastillo** [comment]
This line is synching the device
https://github.com/cupy/cupy/blob/master/cupy/cuda/cufft.pyx#L283-L284

It just calls 
https://docs.nvidia.com/cuda/cufft/index.html#function-cufftmakeplan1d with type as `CUFFT_C2R`
@anaruse @leofang is this expected behavior? plan creation can synchronize the device in this situation?

**Comment by grlee77** [comment]
I think this is just caused by the chosen size of 5,000,000 being particularly unfavorable for `irfft`. Size 5,000,000 would result from a forward `rfft` of a signal of size 9,999,999 which is similarly fairly slow (~100 ms when I timed it).

If I take the irfft of a signal of size 5,000,001 or 2,500,001 for example, I get times around 1 ms which is more in line with the results of the other cases above.

**Comment by grlee77** [comment]
Follow-up: The prime factors of 9,999,999 are [3, 3, 239, 4649], so this involves some large factors that aren't favorable to good FFT-based acceleration.

**Comment by emcastillo** [comment]
Thanks for the follow-up, makes total sense

**Comment by leofang** [comment]
I run nvprof with a loop of `cupy.fft.irfft` and I see that `cufft.Plan1d.__init__()` (the green marker) is taking the majority of time (whereas it isn't for other kinds of FFT). A lot of things happened when allocating an irfft plan:
<img width="1446" alt="截圖 2020-07-06 上午11 01 49" src="https://user-images.githubusercontent.com/5534781/86608196-37b7e200-bf78-11ea-800a-9841ae77d9d6.png">
Note like @emcastillo found `cudaDeviceSynchronize()` is called (highlighted) in `__init__()`, and there're also `cudaMalloc`, `cudaMemcpy`, `cudaFree` taking time. Finally, a few CUDA kernels (`void spRadix...`) are called in `__init__()` as well. Perhaps because of the non-prime-multiple size, cuFFT is taking excessive time and resource to make the preparation?

**Comment by emcastillo** [comment]
cudaDeviceSynchronize seems to be called inside cufft :)

**Comment by asi1024** [comment]
@grlee77 That makes sense. Thanks!
