### ISSUE TITLE
Support for eigvals keyword with eigh

### ISSUE THREAD

**Issue by wakita** [cupy/cupy#360]
It would be great if `eigh` accepts `eigvals=` keyword like [`scipy.linalg.eigh`.](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.eigh.html)

Current, implementation attempts to compute all the eigenvectors.  I only need its small subset; for example eigenvalues that correspond to a few hundred largest eigenvalues.  The ranks of my matrices is about: 10,000 < r < 100,000.

**Comment by wakita** [comment]
I did some research.

Current implementation of `eigh` relies on `dsyevd` from `CuSolver`.  My request can be satisfied if the call is replaced by an api that is compatible with Lapack's `dsyevr`.  Then I realized that `dsyevr` is not included in `CuSolver`, if I understand it correctly.

I could be wrong as I am new to both CuPy and CuSolver.

**Comment by leofang** [comment]
This can be closed.

**Comment by kmaehashi** [comment]
@leofang Is this still a valid feature request to implement `cupyx.scipy.linalg.eigh`?

**Comment by leofang** [comment]
@kmaehashi I believe the original intention of this issue was to add `eigvals` to [`cupy.linalg.eigh`](https://docs.cupy.dev/en/stable/reference/generated/cupy.linalg.eigh.html). But there is already another API [`cupy.linalg.eigvalsh`](https://docs.cupy.dev/en/stable/reference/generated/cupy.linalg.eigvalsh.html) that only returns eigenvalues as requested. Also, this request is against the compatibility policy with NumPy APIs, so I don't think it's doable.

If the intention was to implement `cupyx.scipy.linalg.eigh` (which currently does not exist), then the issue title should be changed 🙂

**Comment by kmaehashi** [comment]
Thanks, makes sense that `cupy.linalg.eigvalsh` can satisfy the requrement.
