### ISSUE TITLE
[Discussion/Question] `tolist` implementation in cupy

### ISSUE THREAD

**Issue by galipremsagar** [cupy/cupy#3615]
We(cudf) are in the middle of disabling(throwing errors) for methods(`__iter__`, `iteritems`, `to_dict`, `tolist`) that will result in device to host transfers. This is similar to how we throw an error currently for `__array__` in cudf & cupy.

So during a [discussion](https://github.com/rapidsai/cudf/issues/5689#issuecomment-658494319) on disabling tolist(in cudf), @jakirkham  pointed out that cupy actually allows calling `tolist` which creates a device to host transfer. Was there any motivation behind allowing `tolist` to return a result and restricting `__array__` ?

**Comment by galipremsagar** [comment]
cc: @pentschev @kkraus14

**Comment by leofang** [comment]
I guess the reason is that `__array__` could perform the device-to-host transfer without users noticing it, whereas `tolist()` does not have this issue (as someone must call `arr.tolist()` explicitly). If downstream libraries do not call `tolist()`, it should be fine.

**Comment by kkraus14** [comment]
I think our fear from the cuDF side is that `tolist()` is a built-in API of numpy / Pandas which only has medium performance impact so code may not have been too afraid or thoughtful in using it. Now with CuPy / cuDF, the performance impact of going to a Python list is catastrophic, but it would be unbeknown to the user as to why they're seeing poor performance because it's hidden underneath a library.

**Comment by jakirkham** [comment]
Well I think it is commonly known that `list`s are not the most performant way of operating with data in Python. Certainly there’s an extra performance hit moving from device to host in the GPU cases, but maybe that already fits in with the `list`s are slow understanding. So I think this mostly gets used when users really want a Python native object in spite of performance issues.
