### ISSUE TITLE
Performance issue : cupy is 800 times slower than numpy in linalg.solve()

### ISSUE THREAD

**Issue by Mirebeau** [cupy/cupy#3931]
Dear cupy team,

I found that the cupy.linalg.solve routine is much slower than the corresponding numpy routine (about 800 times, which makes is unusable), in a very simple and massively parallel instance. Here I solve 10000 linear systems of size 2x2 in parallel.

```console
import numpy as np
import cupy as cp
import time

n=10000 
a = cp.empty((n,2,2),dtype=np.float32)
v = cp.empty((n,2),dtype=np.float32)

a[:,0,0]=a[:,1,1]=1; a[:,1,0]=a[:,0,1]=0
v[0]=0; v[1]=1

t0=time.time()
np.linalg.solve(a,v)
t1=time.time()
np.linalg.solve(a.get(),v.get())
t2=time.time()

t_cupy,t_numpy=t1-t0,t2-t1
print(f"t_cupy={t_cupy}, t_numpy={t_numpy}, ratio={t_cupy/t_numpy}")
```

Output : 
```console
t_cupy=2.396995782852173, t_numpy=0.0030279159545898438, ratio=791.6322047244095
```

OS : Windows
CuPy version : 7.8
Cuda version : 10.2
Graphics card : Nvidia 1080 GTX

Any chance to solve this performance issue ?

-- Full output of cp.show_config() --
CuPy Version          : 7.8.0
CUDA Root             : None
CUDA Build Version    : 10020
CUDA Driver Version   : 11000
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : None
NCCL Runtime Version  : None
CUB Version           : None
cuTENSOR Version      : None

**Comment by anaruse** [comment]
It is not surprising to see such slow performance when solving multiple small linear matrix equations, because the current `cupy.linalg.solve` implementation solves the multiple linear matrix equations one by one.
https://github.com/cupy/cupy/blob/e2b5a3c19f8aec1c4acfda239265ba4e54e5bd60/cupy/linalg/solve.py#L65-L68

Probably, your use case can be significantly improved by using [cublasXgetrfBatched()](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-getrfbatched) and [cublasXgettrsBatched(](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-getrsbatched)).

**Comment by Mirebeau** [comment]
Ok, thanks for the workaround.
It would be nice feature if cupy handled it directly though.
