### ISSUE TITLE
ROCm: Support hipSPARSE/rocSPARSE

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4101]
https://github.com/ROCmSoftwarePlatform/hipsparse
https://github.com/ROCmSoftwarePlatform/rocSPARSE

**Comment by hodgestar** [comment]
[QuTiP](https://github.com/qutip/qutip) and many other quantum physics or computing packages would greatly benefit from having support for ROCm sparse matrices. Operators for quantum systems of `N` qubits (or the equivalent in a more general quantum physics context) are represented by `2**N x 2**N` complex matrices, so even moderately sized systems rapidly outgrow the available RAM on GPUs. Sparse matrices are thus a requirement for simulating many systems, including those currently available in many labs around the world (e.g. current generation quantum computers). 

We have just started a GSoC project to experiment with [CuPy support in QuTiP](https://github.com/qutip/qutip-cupy) and having ROCm support for sparse matrices would allow us to use CuPy as our general solution for QuTiP across almost all GPU-like accelerators rather than only a partial solution.

Other quantum physics libraries are likely in a similar position to us -- they'd like a straight forward way to before GPU accelerated sparse matrix operations across as broad a selection of hardware as possible without having to worry about *too* many of the details ourselves. Our users are typical smart enough to figure out what's needed if we provide support, but we need help to produce good compatible GPU code -- are brains are struggling with enough quantum stuff already without having to also understand all the amazing GPU hardware produced by other smart people!
