### ISSUE TITLE
Raise `NotImplemented` in binary operations with non-CuPy arrays

### ISSUE THREAD

**Issue by pentschev** [cupy/cupy#4118]
Binary operations in CuPy currently raise `TypeError` when `other` is a non-CuPy array, see below:

```python
In [1]: import cupy as cp, dask.array as da

In [2]: a = cp.arange(5)

In [3]: b = da.ones_like(a, shape=(5,))

In [4]: b - a
Out[4]: dask.array<sub, shape=(5,), dtype=int64, chunksize=(5,), chunktype=cupy.ndarray>

In [5]: a - b
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-09bd029d0285> in <module>
----> 1 a - b

cupy/core/core.pyx in cupy.core.core.ndarray.__sub__()

cupy/core/_kernel.pyx in cupy.core._kernel.ufunc.__call__()

cupy/core/_kernel.pyx in cupy.core._kernel._preprocess_args()

TypeError: Unsupported type <class 'dask.array.core.Array'>
```

It would be useful to instead raise a `NotImplemented` exception as it would allow the `other` array to try to compute that operation, see [`NotImplemented` docs](https://docs.python.org/3/library/constants.html#NotImplemented) for details.

Any thoughts on allowing this in CuPy?

**Comment by kmaehashi** [comment]
Thanks for the feedback! Currently CuPy binops only take care of `__array_priority__` (https://github.com/cupy/cupy/blob/v8.0.0/cupy/core/core.pyx#L67-L70 + https://github.com/cupy/cupy/blob/v8.0.0/cupy/core/core.pyx#L1068-L1072) and not following NEP-13 rules like Dask.
https://numpy.org/neps/nep-0013-ufunc-overrides.html#behavior-in-combination-with-python-s-binary-operations
I think we should update the logic to follow it.

**Comment by asi1024** [comment]
NEP-13 says that `self.__op__` return `NotImplemented` when `other.__array_priority__ > self.__array_priority__`, but otherwise calls the corresponding ufunc and it never return `NotImplemented`. Could you set the value of `dask.array.__array_priority__` higher than 100?
https://github.com/dask/dask/blob/0ca77043bbbe015dcb69378ece54419332734f40/dask/array/core.py#L1413)
https://github.com/cupy/cupy/blob/v8/cupy/core/core.pyx#L269

**Comment by pentschev** [comment]
Apologies, I missed responses here.

> Could you set the value of `dask.array.__array_priority__` higher than 100?

I'm guessing we can't as I believe many projects use that and have already higher values specifically because of Dask. @mrocklin could you confirm/deny my statement, or maybe copy someone else who's more familiar with that in Dask?

**Comment by mrocklin** [comment]
100 seems like a very high value.  I think that numpy uses 10 and most other projects use values like 11.

In practice though I also don't know if `__array_priority__` is commonly used.  In cases like this I think that the Python binary operator dance is probably a better fit (try `left.__add__(right)` if that doesn't work then try `right.__radd__(left)`.  However, I do not know how that integrates with NEP-13 (I am not very familiar with NEP-13). 

cc'ing @jakirkham and @seberg , both of whom know this better than I do.

**Comment by seberg** [comment]
Looking at the cupy code, it uses the logic:
```
cdef inline _should_use_rop(x, y):
    xp = getattr(x, '__array_priority__', 0)
    yp = getattr(y, '__array_priority__', 0)
    return xp < yp and not isinstance(y, ndarray)
```

This is different from what NumPy does. NumPy rather first checks for `__array_ufunc__` with the assumption that the `__array_ufunc__` protocol will handle it correctly later (assuming `__array_ufunc__` is not `None`, which means that you should defer always).

My first impression is that cupy should add the check for `__array_ufunc__` to allow fallback to the ufunc/`__array_ufunc__` protocol?  For NumPy that is what happens anyway, I guess for cupy that may mean a 3-way logic (defer, use ufunc, handle internally).

**Comment by seberg** [comment]
From my perspective, array-priority is more of an artifact of the past. We probably can't quite do without it yet, but I think we should try.

Normally, the logic in `__add__` is something like:

```
def __add__(self, other):
    if not is_known_type(other):
        return NotImplemented
```
NumPy (and cupy probably) can't do that easily, because we coerce most python objects agressively.  The solution is to use `__array_ufunc__` to decide whether this is a "coercible" type:
```
def __add__(self, other):
    if hasattr(other, "__array_ufunc__") and not is_known_type(other):
        return NotImplemented
```
NumPy continues to check the array priority for historic reasons IMO.  And I am not even sure cupy/dask have to worry about it?

In the previous post I thought you may need a 3-way logic (calling the ufunc in theory).  I guess that should not be necessary, if `self.__array_ufunc__` is valid, `is_known_type()` will succeed since you use the same logic for `__array_ufunc__`.  If `other.__array_ufunc__` would be used, then `other.__add__` should succeed as well and deferring is correct.

Or am I missing a reason why cupy/dask must rely on `__array_priority__` here?

**Comment by asi1024** [comment]
@pentschev @mrocklin @seberg Thanks for your explanations! I fixed cupy.ndarray binary operation logic in #4198.

**Comment by toslunar** [comment]
```
>>> cupy.ones((3, 4)) @ da.ones_like(cupy.empty((4, 2)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 1197, in cupy._core.core.ndarray.__matmul__
  File "/path/to/cupy/_core/_gufuncs.py", line 660, in __call__
    args, dimsizess, loop_output_dims, outs, m_dims = self._get_args_transposed(  # NOQA
  File "/path/to/cupy/_core/_gufuncs.py", line 474, in _get_args_transposed
    args = [_manipulation.broadcast_to(
  File "/path/to/cupy/_core/_gufuncs.py", line 474, in <listcomp>
    args = [_manipulation.broadcast_to(
TypeError: Argument 'array' has incorrect type (expected cupy._core.core.ndarray, got Array)
```
