### ISSUE TITLE
[Bug Fix] This is an error why I tried to check two columns

### ISSUE THREAD

**Issue by IchiruTake** [cupy/cupy#4197]
Thank you for using and contributing to CuPy!

If your issue is a **request for support in using CuPy**, please post it on [Stack Overflow](https://stackoverflow.com/questions/tagged/cupy) or Google Groups ([en](https://groups.google.com/forum/#!forum/cupy) / [ja](https://groups.google.com/forum/#!forum/cupy-ja)).
Developer team members are monitoring questions on these channels.

If it is a bug report, please include the following information:
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version: 8.0.0 
  - OS/Platform: Windows 10 Pro
  - CUDA version: CUDA 10.1
  - cuDNN/NCCL version (if applicable)

* Code to reproduce
```python
import cupy as cp
a = cp.array([0, 1])
b = cp.array([0, 1])
print(cp.array_equal(a, b))
if cp.array_equal(a, b) is True:
    print("Valid")
else:
    print("Not valid")
```
* Error messages, stack traces, or logs

while it is True, it can not track the result and print Not valid

**Comment by aitikgupta** [comment]
I looked around a bit, leaving a few comments:
```
import numpy as np
import cupy as cp

a, b = cp.array([0, 1]), cp.array([0, 1])
p, q = cp.asnumpy(a), cp.asnumpy(b)

print(type(np.array_equal(p, q)))   # <class 'bool'>
print(type(cp.array_equal(a, b)))   # <class 'cupy.core.core.ndarray'>
```
This is because in [NumPy implementation](https://github.com/numpy/numpy/blob/ab22e0076608f4825bf9a3ca1b6a0a6a7a670d14/numpy/core/numeric.py#L2448), return is casted to `bool`. However, following https://github.com/cupy/cupy/issues/3125#issuecomment-594260606, this is not done here as it synchronizes the device when called.

One workaround in your example is to use:
```
if cp.array_equal(a,b):
    print("Valid")                  # Valid is printed
else:
    print("Not valid")
```
I'm a newbie, I'm not sure how device synchronization is unwanted behaviour here. Maybe @emcastillo could provide some insights?

**Comment by emcastillo** [comment]
```
>>> cp.array_equal(a, b)
array(True)
```
`cp.array_equal` is a cupy array containing `True`, so it is not `True` object, making the comparison fail.
You need to explicitly get the True value by either doing `bool(cp.array_equal(a, b))` or just `if cp.array_equal(a, b)`.
Beware that this triggers device synchronization.
