### ISSUE TITLE
extern "C" Feature Request for RawKernel and RawModule

### ISSUE THREAD

**Issue by veritas9872** [cupy/cupy#4298]
Hello, I would like to request a wrapper for raw CUDA kernels that ensures that `extern "C"` is applied to CUDA source code when using RawKernels and RawModules.

Due to the lack of documentation as of version 8.0, it is difficult for inexperienced users to find out why their functions will not compile.

PyCUDA has a "no_extern_c" flag in its functions that is set to False by default (See [here)](https://documen.tician.de/pycuda/driver.html).

I think that this feature will be helpful for those moving from PyCUDA to CuPy.

**Comment by leofang** [comment]
Hi @veritas9872, thanks for the suggestion, and sorry to hear your frustration from your migration journey. The `extern "C"` usage is demonstrated in the [Tutorial](https://docs.cupy.dev/en/stable/tutorial/kernel.html#raw-kernels) session of the doc. The documentation might not be obvious and certainly has room for improvement, as always.

However, I think your suggestion would lead to backward incompatibility and so likely break existing codes. In particular, my original intention of `RawModule` (#2389, added since CuPy v7.0) was to load external source code, which should already have proper C bindings set up in order to fetch by name. In addition, unlike in PyCUDA our `RawModule` also supports C++ template kernels via `name_expressions`, which does not require an enclosing `extern "C"` block at all. So all these complexities that add up together would make code preprocessing convolved, which is something I strive to avoid as recently mentioned in another (kinda related) issue (#4246). 

Another minor point is PyCUDA's `no_extern_c` flag is a bit unintuitive due to double negativity. 

IMHO the burden is on those who are brave enough to bring custom CUDA C/C++ code to Python, and the intrusion  of `RawKernel`/`RawModule` are kept minimum for performance considerations, with the assumption that these users know what they're doing. The usage and practice here is no different from using the CUDA driver API in C. Just my two cents.

**Comment by leofang** [comment]
Another thing worth noting is that like in most of the CuPy codebase `RawKernel`/`RawModule` are compiled by NVRTC by default (unless `backend='nvcc'` is set), which is a strict C++ compiler. This is another difference from PyCUDA.

**Comment by veritas9872** [comment]
@leofang Thank you for the explanation. 
I could not make my code compile and resorted to using `backend='nvcc'` because NVRTC could not find several header files.
After hearing your explanation, I think that the best solution would be to have better documentation with guides on how to deal with some common pitfalls.
I understand that RawKernel and RawModule are both relatively new and not frequently used. Even after several hours of googling, I could only find a few basic examples with simple kernels, whereas I needed to plug in an entire GitHub repository with CUDA project that was originally designed for MATLAB via mex.
Perhaps a FAQ page or possibly a migration tutorial from PyCUDA could be created. While there are not many users who are doing this right now, despite the many advantages of CuPy over PyCUDA, I believe that a large part of the reason is exactly that there are no in-depth tutorials for implementing raw kernels and CUDA projects into CuPy.

**Comment by veritas9872** [comment]
Also, I believe that many people, such as myself, wish to integrate pre-existing CUDA libraries, instead of writing CUDA code for CuPy per se. For example, I only hoped to integrate a pre-existing CUDA implementation of non-local means.

**Comment by veritas9872** [comment]
Thank you for your help! I will try out CuPy integration a bit more with your suggestions.
