### ISSUE TITLE
Making an array of a list of zero-dimensional arrays

### ISSUE THREAD

**Issue by thomasaarholt** [cupy/cupy#4465]
I'm getting the following error when I call this code:

```python
a = 1
cp.array([[a], [a]]) # works 
a = cp.cos(1) # creates a zero-dimensional array, because there is no GPU-scalar type
cp.array([[a], [a]]) # fails
cp.array([a]) # works

cupy\core\_routines_manipulation.pyx in cupy.core._routines_manipulation.concatenate_method()
TypeError: zero-dimensional arrays cannot be concatenated
```

It works as one would expect on numpy, constructing an array of shape `(2, 1)`.
I suspect this is related to #3819, but while I find some references to it [in the docs](https://docs.cupy.dev/en/stable/reference/difference.html#zero-dimensional-array), I'm surprised that this operation isn't supported. 

Trying with `cp.stack([[a], [a]])` instead leads to a different error, that a list of list doesn't have a ndim attribute. Perhaps this should instead be checking `cp.array(x).ndim` (or `cp.asarray(x).ndim`)?

```python
cp.stack([[a], [a]])

~\Miniconda3\envs\py\lib\site-packages\cupy\_manipulation\join.py in stack(tup, axis, out)
    132     # TODO(okuta) Remove this if exampd_dims is updated
    133     for x in tup:
--> 134         if not (-x.ndim - 1 <= axis <= x.ndim):
    135             raise numpy.AxisError(
    136                 'axis {} out of bounds [{}, {}]'.format(

AttributeError: 'list' object has no attribute 'ndim'
```

  - CuPy version: 8.2.0
  - OS/Platform: Win 10
  - CUDA version: 11.1

**Comment by takagi** [comment]
Thanks for your report, and very sorry for the late response.

CuPy supports only a sequence of `cupy.ndarray` where NumPy supports a sequence of array_like. `cupy.stack` also follows this and takes a sequence of `cupy.ndarray` only for its first argument [as documented](https://docs.cupy.dev/en/stable/reference/generated/cupy.stack.html). `cupy.stack([[a], [a]])`  raises the following error with the current master instead of `AttributeError` with CuPy 8.2.0.

```
TypeError: Argument 'a' has incorrect type (expected cupy.core.core.ndarray, got list)
```

The fact is the same as [this](https://docs.cupy.dev/en/stable/reference/difference.html#universal-functions-only-work-with-cupy-array-or-scalar), but it only says about the universal functions. The part should be updated somehow.

As for `cupy.array([[a], [a]])`, its behavior looks changed after NumPy introduced NEP 18, `__array_function__` protocol. Let us think how it should work again.

**Comment by thomasaarholt** [comment]
Wow, that was impressively quick! Thanks!
