### ISSUE TITLE
Add Windows support in cuTENSOR download tool

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4601]
https://github.com/cupy/cupy/pull/4560#issuecomment-764422155

**Comment by jakirkham** [comment]
@leofang is this just a question of installing 7zip on CI or is there more to it than that?

**Comment by leofang** [comment]
> @leofang is this just a question of installing 7zip on CI or is there more to it than that?

No, it's about how to automate things for users. So for cuDNN, CuPy provides a convenient script so that users can install the wheel from PyPI (which has the cuDNN support built, but does not contain cuDNN itself as the wheel would be oversized) and then run
```
$ python -m cupyx.tools.install_library --library cudnn --cuda 10.0
```
and the script would install cuDNN to CuPy's cache dir so that it can be found and linked at runtime. This works on both Linux and Windows.

For cuTENSOR, the same script works on Linux (done in #4560). But for Windows, this workflow has a problem due to unable to extract `.exe` using only the Python standard library (`shutil.unpack_archive`). This is what https://github.com/cupy/cupy/pull/4560#issuecomment-764422155 is about, also why [I suggested to package it in a format other than `.exe`](https://github.com/cupy/cupy/pull/4617#issuecomment-777032244). I don't see why cuTENSOR has to be packaged in a different way from cuDNN, which just works out of box.

**Comment by springer13** [comment]
@leofang we're planing to replace the .exe with .zip to resolve this issue. I'll update this thread once the .zip file is available.

**Comment by leofang** [comment]
That'd be great, thanks @springer13!

**Comment by springer13** [comment]
The .zip file should be available for download now. Please let us know if this resolved your problem. Thanks

**Comment by leofang** [comment]
Fantastic, @springer13! I confirm the link works. We should be able to start from here.
