### ISSUE TITLE
original error: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Joevaen** [cupy/cupy#4608]
Thank you for using and contributing to CuPy!

If your issue is a **request for support in using CuPy**, please post it on [Stack Overflow](https://stackoverflow.com/questions/tagged/cupy) or Google Groups ([en](https://groups.google.com/forum/#!forum/cupy) / [ja](https://groups.google.com/forum/#!forum/cupy-ja)).
Developer team members are monitoring questions on these channels.

If it is a bug report, please include the following information:

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy 8.4.0
  - OS/Platform: Ubuntu18.04
  - CUDA 10.2
  - cuDNN/NCCL version (if applicable) cudnn 7.6.5
* Code to reproduce
`pip install cupy_cudaxxx`
* Error messages, stack traces, or logs
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
Traceback (most recent call last):
  File "/home/qiao/anaconda3/envs/py3.6/lib/python3.6/site-packages/cupy/__init__.py", line 20, in <module>
    from cupy import core  # NOQA
  File "/home/qiao/anaconda3/envs/py3.6/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qiao/anaconda3/envs/py3.6/lib/python3.6/site-packages/cupy/__init__.py", line 41, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: libcudart.so.10.2: cannot open shared object file: No such file or directory
>>>

**Comment by Joevaen** [comment]
Cupy install failed when I first install it on cuda10.1, so I upgrade cuda to 10.2. It still didn't  work. I use `pip install cupy_cudaxxx`.

**Comment by kmaehashi** [comment]
Could you try using conda-forge packages instead of pip? Conda installation comes with the CUDA toolkit.
https://docs.cupy.dev/en/stable/install.html#installing-cupy-from-conda-forge

When using pip packages, you may need to set `LD_LIBRARY_PATH` depending on how you installed CUDA.
https://docs.cupy.dev/en/stable/install.html#working-with-custom-cuda-installation

**Comment by Joevaen** [comment]
Hi, kmaehashi.
I have set the LD_LIBRARY_PATH in my .bashrc. it looks right and `nvcc -V`has correct output.
![image](https://user-images.githubusercontent.com/46133615/106709376-62156f00-662f-11eb-962c-827fa1d166f1.png)
As for conda installation. I have tried it but it will install nvidia-cuda-tookit again(I have cuda on my OS). Is this normal?
after I conda, it still didn't work.
Sad.

**Comment by leofang** [comment]
Could you post the full command you ran for `conda install`, and also the output of `conda list`?

As for pip, your command does not seem right. It should be `pip install cupy-cuda102` (with a hyphen, not underscore). Perhaps it was simply a typo?

**Comment by Joevaen** [comment]
1.`pip install cupy-cuda102` has same output with `pip install cupy_cuda102`.
2. I use `conda install -c conda-forge cupy` to install cupy via conda and I found it worked in a new conda env, but it didn't work in base env with a error says `RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.
RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.`

**Comment by Joevaen** [comment]
> 1.`pip install cupy-cuda102` has same output with `pip install cupy_cuda102`.
> 2. I use `conda install -c conda-forge cupy` to install cupy via conda and I found it worked in a new conda env, but it didn't work in base env with a error says `RemoveError: 'requests' is a dependency of conda and cannot be removed from conda's operating environment. RemoveError: 'setuptools' is a dependency of conda and cannot be removed from conda's operating environment.`

`conda update --force conda` before `conda install -c conda-forge cupy`solved.

**Comment by leofang** [comment]
> 1.`pip install cupy-cuda102` has same output with `pip install cupy_cuda102`.

Something must be wrong, because the former is what is supported. If you post the full logs here we'll be able to diagnose.

> 2. I use `conda install -c conda-forge cupy` to install cupy via conda and I found it worked in a new conda env, but it didn't work in base env with a error says `RemoveError: 'requests' is a dependency of conda and cannot be removed from conda's operating environment. RemoveError: 'setuptools' is a dependency of conda and cannot be removed from conda's operating environment.`

It could be that it requires a more recent version for these dependencies, in conflict with the base env. In general, it is a very bad practice to touch Conda's base env, and it's expected that users always create a new env to install packages. The base env is to manage minimal dependencies required for `conda install` etc to work.

btw it's better to install from the `conda-forge` channel, because it's what we maintain and have full control over.

To your earlier question:    
> As for conda installation. I have tried it but it will install nvidia-cuda-tookit again(I have cuda on my OS). Is this normal?

Yes. Installing `cupy` from Conda will also install CUDA runtime library (`cudatoolkit`). If you insist on using your local CUDA, you should create a Conda env with at least `numpy` and `fastrlock` installed, and then do `pip install cupy-cuda102`. Installing from PyPI will attempt to link to your local CUDA at runtime.
