### ISSUE TITLE
Creating a cupy device array from GPU Pointer

### ISSUE THREAD

**Issue by ax3l** [cupy/cupy#4644]
Hi,

we develop a GPU-accelerated C++ code with Python bindings called [WarpX](https://github.com/ECP-WarpX/WarpX).

If we are compiling for CPU, we currently expose our memory for user-side manipulation as numpy arrays, adopting the existing, C++-side managed memory directly via `numpy.frombuffer` [[code]](https://github.com/ECP-WarpX/WarpX/blob/1f8ab0e625f27e9201b0da9dcfbab52c30112089/Python/pywarpx/_libwarpx.py#L127-L130):
```py
        PyBUF_WRITE = 0x200
        buffer_from_memory = ctypes.pythonapi.PyMemoryView_FromMemory
        buffer_from_memory.argtypes = (ctypes.c_void_p, ctypes.c_int, ctypes.c_int)
        buffer_from_memory.restype = ctypes.py_object
        buf = buffer_from_memory(pointer, dtype.itemsize*size, PyBUF_WRITE)
```

Looking at the cupy `_generate` functions and `cupy.ndarray` constructors, it is not immediately clear to us how we can create a non-owning cupy array in the same way. Do you have any hints/workflows on that? We found that there is no [frombuffer](https://docs.cupy.dev/en/stable/reference/comparison.html) equivalent in cupy.

We saw #3431 for mmaping a host-side binary into a device-side cupy array but are not fully sure if this is similar enough.

Alternatively, we currently considered creating a numpy array that points to a device-side pointer for its data, a strategy that worked for us for GPU-GPU code coupling as a wrapper before, but now wonder if we can make this a proper cupy array with functions like `cupy.asarray(numpy_array_w_device_ptr)`. Would this adopt or copy out the data and should we add further flags to describe our GPU memory (ownership)?

Thank you already for your feedback!

**Comment by leofang** [comment]
There's a `UnownedMemory` class that can wrap a foreign device pointer and create a CuPy array on top of it, if it's what you're asking for. Check it out how CuPy talks to other libraries through the [CUDA Array Interface](https://numba.readthedocs.io/en/latest/cuda/cuda_array_interface.html):
https://github.com/cupy/cupy/blob/a5b24f91d4d77fa03e6a4dd2ac954ff9a04e21f4/cupy/core/core.pyx#L2478-L2514
`ptr` there is the pointer address (cast to `intptr_t`, which is also representable as a simple Python int). A nicer thing you can do is to support `__cuda_array_interface__` in your Python layer 🙂 Let me know if this helps.

**Comment by ax3l** [comment]
Thank you for the advice, this looks great and is exactly what we were looking for.

We will then implement the CUDA Array Interface (v3) through pybind11 in AMReX and downstream codes.

I read in the docs that there is no convention on the C-side yet, I wonder if it makes sense to follow one for general pybind11 helpers. Here is how they look for the array interface / buffer protocol: [Py](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html) / [C++](https://github.com/pybind/pybind11/blob/v2.6.2/include/pybind11/buffer_info.h#L39-L48)

**Comment by leofang** [comment]
> I read in the docs that there is no convention on the C-side yet, I wonder if it makes sense to follow one for general pybind11 helpers. Here is how they look for the array interface / buffer protocol: [Py](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html) / [C++](https://github.com/pybind/pybind11/blob/v2.6.2/include/pybind11/buffer_info.h#L39-L48)

Hi @ax3l, sorry I dropped the ball. So, yes, `__cuda_array_interface__` is a Python-only protocol. If you already support buffer protocol (at the C level) and you'd like to incorporate `__cuda_array_interface__`, we actually did this in mpi4py:
https://github.com/mpi4py/mpi4py/blob/28eb557182bed368701165f99788bd2497d59f42/src/mpi4py/MPI/asgpubuf.pxi#L59
So if you check the function `Py_GetCUDABuffer` there, what we did was to parse the content in `__cuda_array_interface__` and convert it to a Python buffer object (which we already supported since very early days of mpi4py) to use the existing infrastructure. Not sure if this is useful to you, though.

Another option is to support DLPack. It exposes some C structs all the way up to the Python level. Check out how we support it in CuPy here: https://github.com/cupy/cupy/blob/master/cupy/core/dlpack.pyx This exchange protocol will be part of the upcoming Python Array API standard: https://data-apis.github.io/array-api/latest/design_topics/data_interchange.html
The good thing of the DLPack protocol is that it aims to support a wide spectrum of architectures (CPU, NVIDIA GPU, AMD GPU, Intel GPU, etc), but the bad thing IMHO is it's a bit more involved than `__cuda_array_interface__`.

**Comment by Char-Aznable** [comment]
@leofang I am running into errors when following the above example to wrap a cp.ndarray from a CUDA device pointer exported by pybind11. Here's the minimal reproducing case. I have a CUDA c++ class that host a device pointer:

header:
```c++
#include <cstdint>

struct A {
  A();

  ~A();

  int *p_;

  intptr_t getDevicePointer() const;
};
```

implementation:
```c++
#include <arrayPointer.hpp>
#include <cstdint>

A::A() {
  cudaMalloc((void**)&p_, 10 * sizeof(int));
  cudaMemset((void*)p_, 0, 10 * sizeof(int));
  cudaDeviceSynchronize();
}

A::~A() {
  cudaFree((void*)p_);
}

intptr_t A::getDevicePointer() const {
  return reinterpret_cast<intptr_t>(p_);
}
```

and the pybind11 export:
```c++
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_MODULE(arrayPointer_pybind, m) {
  m.doc() = "Test passing CUDA device memory pointer to cupy array";

  py::class_<A>(m, "A")
    .def(py::init())
    .def("getDevicePointer", &A::getDevicePointer)
    ;

}

```
I have this simple python test code:

```python
#!/usr/bin/env python3
import cupy as cp
import arrayPointer_pybind
from cupy.cuda.memory import MemoryPointer, UnownedMemory


def pDevice2CuPyArray(pDevice : int, span : int, dtype : type, owner=None):
    mem = UnownedMemory(pDevice, span, owner)
    memptr = cp.cuda.MemoryPointer(mem, 0)
    return cp.ndarray(span, dtype=float, memptr=memptr)


a = arrayPointer_pybind.A()

pDevice = a.getDevicePointer()
arrDevice = pDevice2CuPyArray(pDevice, 10, cp.int32)

```
but doing things like `print(arrDevice)`  gives error:
```python
CUDARuntimeError                          Traceback (most recent call last)
Input In [15], in <cell line: 1>()
----> 1 print(arrDevice)

File cupy/_core/core.pyx:1729, in cupy._core.core._ndarray_base.__str__()

File cupy/_core/core.pyx:1840, in cupy._core.core._ndarray_base.get()

File cupy/cuda/memory.pyx:562, in cupy.cuda.memory.MemoryPointer.copy_to_host()

File cupy_backends/cuda/api/runtime.pyx:580, in cupy_backends.cuda.api.runtime.memcpy()

File cupy_backends/cuda/api/runtime.pyx:143, in cupy_backends.cuda.api.runtime.check_status()

CUDARuntimeError: cudaErrorInvalidValue: invalid argument

```
also `arrDevice.sum()` gives random garbage value while I am expecting the sum is zero because of the `cudaMemset`. 

Am I missing something here?

**Comment by leofang** [comment]
Your `span` is wrong, it should be the total number of bytes. Also, the dtype is wrong, it should be int32, not float.

**Comment by Char-Aznable** [comment]
Thank @leofang for pointing out my mistakes! I updated my snippet and it works great!
