### ISSUE TITLE
Support `like` keyword argument in `cupy.ascontiguousarray` etc.

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5303]
It was introduced in NumPy 1.20.
https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html#numpy.ascontiguousarray

https://numpy.org/neps/nep-0035-array-creation-dispatch-with-array-function.html#nep35

(Maybe only thing we can do is just ignore the argument?)

**Comment by leofang** [comment]
No, the `like` argument is meant to exist only in NumPy so that the NEP-35 dispatch mechanism can be used. I don't think downstream libraries should support it, at least not us:
> https://numpy.org/neps/nep-0035-array-creation-dispatch-with-array-function.html#implementation
> Downstream libraries thus do not require to include the like= keyword to their array creation APIs. In some cases (e.g., Dask), having the like= keyword can be useful, as it would allow the implementation to identify array internals. As an example, Dask could benefit from the reference array to identify its chunk type (e.g., NumPy, CuPy, Sparse), and thus create a new Dask array backed by the same chunk type, something that’s not possible unless Dask can read the reference array’s attributes.

but @pentschev can correct me since this NEP is mostly his work 😁

**Comment by pentschev** [comment]
Leo is correct. We intentionally introduced the argument in that way so that downstream libraries such as CuPy don't need to implement it, nor break in any way due to not implementing the argument. That is an argument that is mostly useful for libraries such as Dask, where we can ensure that new arrays created internally will be dispatched to a downstream library --  such as CuPy -- based on a reference input array.

Ignoring `like=` is the correct way to deal with it in CuPy.

@kmaehashi do you think the existing NEP-35 and API documentation are unclear to library developers such as you? If so, could you point to some part that is unclear so we can try to clarify for future readers that the argument should indeed be ignored?

**Comment by kmaehashi** [comment]
@leofang, @pentschev Thank you for the comments! I think the NEP is written really clearly 😃 
I'm thinking that in principle it's better to keep `cupy` module interchangeable with `numpy` module in code level, i.e. making `xp.ascontiguousarray(a, like=cupy_array)` (where xp can be numpy or cupy) runnable, although I understand it doesn't make much sense in this case.

**Comment by pentschev** [comment]
Thanks for the feedback. I also agree it doesn't make sense, `like=` is specifically targeted at the NumPy dispatching mechanism with `__array_function__`, and although adding it would work we tried to make it clear that it's intended for library developers who want to rely on the NumPy API through `__array_function__`. Implementing is allowed but unnecessary for CuPy, this design was thought specifically to simplify maintenance of downstream libraries as getting the `like=` implementation correct can be challenging, note that similarly to NumPy you would need to remove the `like=` kwarg before dispatching.

There are some [potential uses for that in upstream libraries such as Dask](https://numpy.org/neps/nep-0035-array-creation-dispatch-with-array-function.html#reading-the-reference-array-downstream), but this is completely unnecessary for CuPy today.

**Comment by kmaehashi** [comment]
Thanks for sharing the context. Adding `like` in CuPy won't make sense or rather confusing to users. Let me close this.

**Comment by leofang** [comment]
@kmaehashi Another note: A dispatching mechanism like NEP-35 would no longer be needed once the support for Python array API (#4789) is up. This is in fact one of the many reasons to standardize the array API. I was told during one of the API meetings that there are some complaints for the overhead of `__array_function__` dispatching, but I haven't found a reference issue so far.

**Comment by pentschev** [comment]
> @kmaehashi Another note: A dispatching mechanism like NEP-35 would no longer be needed once the support for Python array API (#4789) is up.

Only true if the entire PyData community backs that. AFAIK, there haven't been any projects so far who actually started using it, whereas CuPy and Dask pretty much "pioneered" the use of `__array_function__`, my opinion is that we need to see more engagement from other projects to think it's viable to make a switch.

> This is in fact one of the many reasons to standardize the array API. I was told during one of the API meetings that there are some complaints for the overhead of `__array_function__` dispatching, but I haven't found a reference issue so far.

I've also heard that in the past, but even then it doesn't seem to have created a highly noticeable impact, otherwise there would be much more outcry from angry users. Therefore, it seems to me that this was more of an issue to very specific use cases.

**Comment by leofang** [comment]
> Only true if the entire PyData community backs that. AFAIK, there haven't been any projects so far who actually started using it, whereas CuPy and Dask pretty much "pioneered" the use of `__array_function__`, my opinion is that we need to see more engagement from other projects to think it's viable to make a switch.

No there aren't any yet, because the Array API v1 standard is not fully finalized, and the implementation is still ongoing 😄 But I do think there is strong commitment at least from NumPy, PyTorch, and CuPy. I am trying to prioritize my work so that we can get the bulk of it done in CuPy v10.

> Therefore, it seems to me that this was more of an issue to very specific use cases.

Yup.

**Comment by pentschev** [comment]
> No there aren't any yet, because the Array API v1 standard is not fully finalized, and the implementation is still ongoing 😄 But I do think there is strong commitment at least from NumPy, PyTorch, and CuPy. I am trying to prioritize my work so that we can get the bulk of it done in CuPy v10.

Yeah, but from a Dask perspective I would really like to see more projects that don't implement `__array_function__` to actually support this new standard. CuPy is often the first one to get such new features in and that's great, but Dask can already interface well with CuPy today. For the time commitment this will require, IMO there will need to be additional advantages in supporting that, namely the possibility to have Dask interfacing with other libraries, but that requires those  libraries to introduce support first.

**Comment by leofang** [comment]
> > No there aren't any yet, because the Array API v1 standard is not fully finalized, and the implementation is still ongoing 😄 But I do think there is strong commitment at least from NumPy, PyTorch, and CuPy. I am trying to prioritize my work so that we can get the bulk of it done in CuPy v10.
> 
> Yeah, but from a Dask perspective I would really like to see more projects that don't implement `__array_function__` to actually support this new standard. CuPy is often the first one to get such new features in and that's great, but Dask can already interface well with CuPy today. For the time commitment this will require, IMO there will need to be additional advantages in supporting that, namely the possibility to have Dask interfacing with other libraries, but that requires those libraries to introduce support first.

I would think the order should be reversed (@jakirkham can correct me since he's also joined the API meeting recently representing Dask): In order for other libraries to use Dask as a backend in their routines, Dask should support the Array API first. Then, if a backend registration system is devised (sorry I can't link to the internal issue), a library can just implement the routines solely with the array API. Of course this is still a long way to go (ex: Is SciPy going to do this rewrite?) but it's the goal 😄

**Comment by pentschev** [comment]
Yes, what I meant to say is I would like to see those libraries committing to implementing the new standard. If Dask goes through all the work of supporting the standard (as it did for `__array_function__`) but no new libraries do, then the effort has been mostly wasted. Of course, that isn't to say that someone with lots of free time in their hands couldn't implement the standard in Dask regardless of that. 🙂

**Comment by leofang** [comment]
Ah yes, right I would love to see at least SciPy and scikit-image commit to it...

**Comment by pentschev** [comment]
Yes, that would be great indeed!
