### ISSUE TITLE
JIT: float16 scalar inputs are not inferred correctly

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5346]
For example:
```python
import cupy as cp
from cupyx import jit

@jit.rawkernel()
def f(a, b):
    x = jit.grid(1)
    a[x] += b


a = cp.empty((32,), dtype=cp.float64)
b = cp.float64(100)
f[1, 32](a, b)

a = cp.empty((32,), dtype=cp.float16)
b = cp.float16(100)
f[1, 32](a, b)
for k, v in f.cached_codes.items():
    print(v)
```
the argument `b` of the 2nd kernel is not typed as `float16` but instead as `float`:
```
extern "C" __global__ void f(CArray<double, 1, true, true> a, double b) {
  unsigned int x;
  x = threadIdx.x + blockIdx.x * blockDim.x;
  a[x] = (a[x] + b);
}

extern "C" __global__ void f(CArray<float16, 1, true, true> a, float b) {
  unsigned int x;
  x = threadIdx.x + blockIdx.x * blockDim.x;
  a[x] = (a[x] + b);
}
```
Looks like this only happens with (Python) scalar inputs; CuPy array inputs are working properly.

**Comment by kmaehashi** [comment]
I heard from @asi1024 that this is intentional, I think he can follow up on the context behind the design.

**Comment by asi1024** [comment]
@leofang 
Yes, this design is intentional as @kmaehashi says.

The float16 class defined in [carray.cuh](https://github.com/cupy/cupy/blob/v9/cupy/_core/include/cupy/carray.cuh#L69) does not define arithmetic operations. For arithmetic operations, an implicit cast to a float is performed, and the result is returned as a 32-bit float value. This was intentionally designed because float16 arithmetic operations don't improve the performance of elementwise operation (because memory accesses take much more time) and introduce large numerical errors. So I designed CuPy JIT to use `float` type for float16 scalar too.

However, this specification is certainly confusing. Ideally, CuPy JIT should use CUDA `half` type as scalar instead of float16, but we need to work on tying many CUDA intrinsic half functions to CuPy ufunc...

**Comment by vsraptor** [comment]
Will the following work on GPU:

```

In [179]: x = np.random.randint(0,100,(10,5), dtype=np.int16)                                                                                                                

In [180]: y = x[:,4].view(dtype=np.float16)

In [188]: y[:] = 0                                                                                                                                                                  
Out[188]: 
array([[97, 14, 75, 42,  0],
       [30, 87, 78, 62,  0],
       [23, 92, 90, 37,  0],
       [15, 12, 58, 36,  0],
       [21, 32, 88, 83,  0],
       [99, 70, 92, 16,  0],
       [ 3, 88, 93, 16,  0],
       [52, 32, 24, 15,  0],
       [52, 99, 17, 97,  0],
       [20, 33, 59, 56,  0]], dtype=int16)  

In [191]: y                                                                                                                                                                  
Out[191]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float16)
```

**Comment by asi1024** [comment]
@vsraptor Yes!
