### ISSUE TITLE
cupy.flip() will change stride causing issues to convert cupy array to tensorflow

### ISSUE THREAD

**Issue by llodds** [cupy/cupy#5665]
I am using cupy to write a simple 3D data augmentation module, but I found cupy.flip() will change stride causing issues to convert cupy array back to TF. This issue only happens with cupy.flip(). shift(), rotate() are doing good. Can someone take a look at this please? Thanks.

This code works:
```python
import tensorflow as tf
import cupy as cp
b = tf.random.uniform((10,))
a = cp.arange(10)
cap = a.toDlpack()
b = tf.experimental.dlpack.from_dlpack(cap)
```
But if I flip array `a`, then it doesn't
```python
c = cp.flip(a)
cap = c.toDlpack()
b = tf.experimental.dlpack.from_dlpack(cap)

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-8-486d3fc9c321> in <module>
      1 c = cp.flip(a)
      2 cap = c.toDlpack()
----> 3 b = tf.experimental.dlpack.from_dlpack(cap)

/hpc/apps/pyhpc/dist/conda/x86_64/envs/cuda-11.0/lib/python3.8/site-packages/tensorflow/python/dlpack/dlpack.py in from_dlpack(dlcapsule)
     64     A Tensorflow eager tensor
     65   """
---> 66   return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)

InvalidArgumentError: Invalid strides array from DLPack
```
So, I have to manually do the flip:
```python
c = cp.copy(a)
c[..., :] = a[..., ::-1]
cap = c.toDlpack()
b = tf.experimental.dlpack.from_dlpack(cap)
```

Conditions
```
CuPy Version          : 8.0.0
CUDA Root             : /hpc/apps/RHEL/3.10/x86_64/cuda/11.0
CUDA Build Version    : 11000
CUDA Driver Version   : 11020
CUDA Runtime Version  : 11000
cuBLAS Version        : 11200
cuFFT Version         : 10201
cuRAND Version        : 10201
cuSOLVER Version      : (10, 6, 0)
cuSPARSE Version      : 11101
NVRTC Version         : (11, 0)
Thrust Version        : 100909
CUB Build Version     : 100909
cuDNN Build Version   : 8000
cuDNN Version         : 8000
NCCL Build Version    : 2708
NCCL Runtime Version  : 2708
cuTENSOR Version      : None
* Code to reproduce
```

**Comment by kmaehashi** [comment]
Thanks for the feedback! I think this is due to that TensorFlow does not support negative strides.

```py
>>> import cupy as cp
>>> a = cp.arange(10)
>>> c = cp.flip(a)
>>> c.strides
(-8,)
```

(DLPack spec defines strides in [`int64_t`](https://github.com/dmlc/dlpack/blob/main/include/dlpack/dlpack.h#L170) but it seems implementation-dependent whether to support negative strides... maybe @leofang knows better 😃 )

The workaround is to make a C-contigous copy like `c.copy().toDlpack()`.

**Comment by llodds** [comment]
But why flip changes the stride? I don't think it should.

**Comment by leofang** [comment]
@llodds Could you bring this issue to TF's repo instead? Thanks.

> but it seems implementation-dependent whether to support negative strides... 

If an implementation decides to not support negative strides (which is odd), it should normalize the strides on the fly when parsing data from DLTensor.

> But why flip changes the stride? I don't think it should.

No, it is natural to do so because changing strides is so cheap (no need to touch the real data). Basically it returns a view of the original array.

**Comment by kmaehashi** [comment]
Let me close this as this is not an issue of CuPy.

FYI, we are in general designing CuPy to align the behavior with NumPy:

```py
>>> import numpy as np
>>> a = np.arange(10)
>>> c = np.flip(a)
>>> c.strides
(-8,)
```
