### ISSUE TITLE
Multithreaded cufft memory leak

### ISSUE THREAD

**Issue by djbarbalato** [cupy/cupy#6355]
### Description

The cufft plan cache does not appear to deallocate GPU memory during thread clean up (GC).  If I launch `cp.fft.fft` on a thread and then exit/join the thread, there is residual memory still allocated on the GPU.

### To Reproduce

```py
from concurrent.futures import ThreadPoolExecutor
import cupy as cp

def task():
    data = cp.ones(2**20)
    return cp.fft.fft(data)

while True:
    with ThreadPoolExecutor(max_workers=3) as executor:
        tasks = [executor.submit(task) for _ in range(10)]
        
    cp.get_default_memory_pool().free_all_blocks()
    cp.get_default_pinned_memory_pool().free_all_blocks()
    cp.fft.config.get_plan_cache().clear()
    
    input("Check nvidia-smi memory usage... Press any key to run again")

```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.29
Python Version               : 3.8.10
CuPy Version                 : 10.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.5
SciPy Version                : 1.7.3
Cython Build Version         : 0.29.24
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : None
CUDA Build Version           : 11040
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11040
cuBLAS Version               : (available)
cuFFT Version                : 10502
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 101201
CUB Build Version            : 101201
Jitify Build Version         : 60e9e72
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : 21104
NCCL Runtime Version         : 21104
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Quadro RTX 5000
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0

```

### Additional Information

Runtime is within docker image `nvidia/cuda:11.4.2-runtime-ubuntu20.04`

**Comment by leofang** [comment]
The plan cache is per thread, per device, so if you wanna clean it up you need to do so in the calling thread (before join).

Lately I've been considering how to force it cleared via `mempool.free_all_blocks()` but no real progress is made so far.

**Comment by leofang** [comment]
The problem here is (by definition) there's no way to clean up a thread-local storage by any other threads when the associated thread is killed.

In CuPy a typical TLS is implemented this way:
```cython
cdef object _thread_local = threading.local()

cdef class _ThreadLocal:
    cdef list stuff_to_be_cached

    def __init__(self):
        ...

    @staticmethod
    cdef _ThreadLocal get():
        try:
            tls = _thread_local.tls
        except AttributeError:
            tls = _thread_local.tls = _ThreadLocal()
        return <_ThreadLocal>tls
```
and in this case we put FFT plans in `stuff_to_be_cached`. This has a memory leak because `_thread_local.tls` is only visible to the creating thread; if the thread is joined (killed) there's no reference to its `_thread_local.tls` that can be accessed by other threads. Therefore, with the current design the plan cache must be cleared before join.

For several places in the CuPy codebase this works fine, because we only store metadata in the TLS whose actual resource is managed elsewhere; there's still a few leaked bytes, yes, but in reality it's not causing trouble unlike FFT plans.

I tried setting a callback to delete `_thread_local.tls` before a thread is joined but it's not working, so I can only see two ways out:
1. Remove the per-thread property of the cache (which breaks backward compatibility)
2. Add a note to the plan cache docs (which keeps backward compatibility)

**Comment by leofang** [comment]
> so I can only see two ways out:
> 
> 1. Remove the per-thread property of the cache (which breaks backward compatibility)
> 2. Add a note to the plan cache docs (which keeps backward compatibility)

The 3rd option I can think of is instead of putting `stuff_to_be_cached` in the TLS (or more precisely, [`per_device_cufft_cache`](https://github.com/cupy/cupy/blob/6bb7576a3e5f518ee0d3a2736e71ffeb02431c75/cupy/fft/_cache.pyx#L25)) we put it in a global dict indexed by the `Thread` objects. This allows other threads to help purge dead threads' caches.

**Comment by carterbox** [comment]
I think this third option is better because it allows for better debugging? For example, `cp.fft.config.show_plan_cache_info()` can show caches from multiple devices but not multiple threads. If we had this third option, then we would be able to see the cache info from all threads and all devices. It's hard to figure out that the plan cache is causing a memory leak when `show_plan_cache_info()` cannot show that terminated threads are still using the cache.

**Comment by leofang** [comment]
There's a chance that if we move to Cython 3 this discussion is moot, as in Cython 3 the cdef classes could be properly cleaned up with `__del__`. But I don't yet have time to look into it...

Update: I found through a stress test that even though a thread is dead, the plan cache that it holds can still be cleaned up when reaching the memory limit. Apparently not only the dead thread's local storage but something else (maybe the memory pool, for some reason?) also holds a reference to the cache.

**Comment by carterbox** [comment]
> plan cache that it holds can still be cleaned up when reaching the memory limit

Automatically? That is not what I observed. The only reason I noticed this memory leak was that I was getting out of memory errors.

**Comment by leofang** [comment]
Hi @carterbox @djbarbalato sorry for the long silence. I've done some research and experiments intermittently over the past few months whenever I got a chance, and it turns out the fix is quite simple (just implement `__dealloc__`), see #6704. 

It was not done when I added the cache because I was under the impression that [calling self's methods is not OK in `__dealloc__`](https://cython.readthedocs.io/en/stable/src/userguide/special_methods.html#finalization-method-dealloc), but apparently `cdef` methods are fine...

Anyway, it'd be nice if either of you could help verify the patch. Thanks!

**Comment by leofang** [comment]
lol I am happy to help if you post the error log, my guess is building from a clean repo would help...

**Comment by carterbox** [comment]
The logs are very long, but the first error is:

```
cupy_backends/cuda/libs/cusparselt.cpp:1469:22: error: 'cusparseLtMatDescAttribute_t' does not name a type; did you mean 'cusparseLtMatmulAlgAttribute_t'?
```
I started with the cupy-feedstock and swapped the source to:

```yaml
source:
  git_url: https://github.com/leofang/cupy.git
  git_tag: fix_fft_cache_leak3
  git_depth: 1 # (Defaults to -1/not shallow)
```

**Comment by leofang** [comment]
Could you try building it locally? I think you used to have cuSPARSELt present at built time so `cupy_backends/cuda/libs/cusparselt.cpp` was generated, but it no longer exists in the search path. 
```
git clone --recursive -b fix_fft_cache_leak3 https://github.com/leofang/cupy.git
cd cupy/
pip install -v -e .
```

**Comment by carterbox** [comment]
OK. I tested it. `cupy=10.4.0` runs out of memory with the script above, but does not run out of memory with your patched branch.

**Comment by leofang** [comment]
Thanks, Daniel!
