### ISSUE TITLE
setup.py seems to be expecting GCC

### ISSUE THREAD

**Issue by JBlaschke** [cupy/cupy#6589]
### Description

When setting `CC` and `CXX` to non-gcc compilers -- eg `nvcc` -- the setup.py build breaks because it is passing GCC-only flags to CC. For example this works on NERSC's Perlmutter (https://docs.nersc.gov/systems/perlmutter/) system:

```bash
blaschke@muller:login02:~> LDFLAGS="$CRAY_CUDATOOLKIT_POST_LINK_OPTS" NVCC="nvcc $CRAY_CUDATOOLKIT_INCLUDE_OPTS" CC=cc CXX=CC pip install cupy
```
when loading:
```bash
module load PrgEnv-gnu
```
as this will set `cc=gcc` and `CC=g++`. However loading:
```bash
module load PrgEnv-ndivida
```
will set `cc=nvcc` and `CC=nvc++`. And the command above will break because the `-fwrapv` flag is passed to `cc` (i.e. `nvcc`) which doesn't know what to do with the flag:
```
    -------- Configuring Module: cuda --------
    nvc-Error-Unknown switch: -fwrapv
    command 'cc' failed with exit status 1
    nvc-Error-Unknown switch: -fwrapv
    **************************************************
    *** WARNING: Cannot check compute capability
    command 'cc' failed with exit status 1
    **************************************************

    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************

    Build Environment:
      Include directories: ['/tmp/pip-install-io1hkbby/cupy_93b134b374a5423fa60a2e4e1263db36/cupy/_core/include/cupy/cub', '/tmp/pip-install-io1hkbby/cupy_93b134b374a5423fa60a2e4e1263db36/cupy/_core/include', '/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/include']
      Library directories: ['/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/lib']
      nvcc command       : ['nvc', '-I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/include', '-I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/nvvm/include', '-I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/Debugger/include', '-I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/CUPTI/include', '-I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/math_libs/11.5/include']
      hipcc command      : (not found)

    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/nvvm/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/Debugger/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/CUPTI/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/math_libs/11.5/lib64 -Wl,--as-needed,-lcupti,-lcudart,--no-as-needed -lcuda
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : nvc -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/include -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/nvvm/include -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/Debugger/include -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/CUPTI/include -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/math_libs/11.5/include
      HIPCC           : (none)
      ROCM_HOME       : (none)

    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.

    ERROR: CUDA could not be found on your system.

    HINT: You are trying to build CuPy from source, which is NOT recommended for general use.
          Please consider using binary packages instead.

    Please refer to the Installation Guide for details:
    https://docs.cupy.dev/en/stable/install.html

    ************************************************************
```

### To Reproduce

Log into NERSC's Perlmutter system.

* This works:

```bash
user@perlmutter:login02:~> module load PrgEnv-gnu
user@perlmutter:login02:~> module load cudatoolkit
user@perlmutter:login02:~> module load python
user@perlmutter:login02:~> LDFLAGS="$CRAY_CUDATOOLKIT_POST_LINK_OPTS" NVCC="nvcc $CRAY_CUDATOOLKIT_INCLUDE_OPTS" CC=cc CXX=CC pip install cupy --user
```

* This doesn't work:

```bash
user@perlmutter:login02:~> module load PrgEnv-nvidia
user@perlmutter:login02:~> module load cudatoolkit
user@perlmutter:login02:~> module load python
user@perlmutter:login02:~> LDFLAGS="$CRAY_CUDATOOLKIT_POST_LINK_OPTS" NVCC="nvcc $CRAY_CUDATOOLKIT_INCLUDE_OPTS" CC=cc CXX=CC pip install cupy --user
```

### Installation

Source (`pip install cupy`)

### Environment

N/A -- this is a compile problem

**Comment by leofang** [comment]
I am pretty sure "-fwrapv" is generated somewhere other than CuPy. Most likely from the Perlmutter Python env which conflicts with nvc++, see this issue and the solution therein: https://github.com/mpi4py/mpi4py/issues/114

Also, the Perlmutter instruction recommends to install CuPy wheel from PyPI:
https://docs.nersc.gov/development/languages/python/using-python-perlmutter/#cupy
Although the instruction may not be fully up-to-date due to the nature of the rapidly changing Perlmutter environment. Maybe opening a ticket with the admin for consultation? 🙂

**Comment by JBlaschke** [comment]
Thanks for the related issue @leofang ... pretty much every time I have a HPC python problem, I get directed to an issue from @ax3l 😉 

Anyway, in this case the `-noswitcherror` in combination with compiler wrappers (nor nvc/nvc++) still doesn't work. In this case it seems to have trouble finding its own standard lib 😞 

```
    -------- Configuring Module: cuda --------
    nvc-Warning-Unknown switch: -fwrapv
    "/tmp/tmp1mjffzr4/a.cpp", line 9: warning: last line of file ends without a newline
      int main() {return 0;}
                            ^

    "/tmp/tmp1mjffzr4/a.cpp", line 9: warning: use of non-prototype function declarator
      int main() {return 0;}
          ^

    /usr/bin/ld: read in flex scanner failed
    Cannot build a stub file.
    Original error: command 'nvc' failed with exit status 2
    nvc-Warning-Unknown switch: -fwrapv
    "/tmp/tmpn4ub4z8r/a.cpp", line 6: warning: use of non-prototype function declarator
              int main() {
                  ^

    "/tmp/tmpn4ub4z8r/a.cpp", line 10: error: identifier "cudaDeviceProp" is undefined
                    cudaDeviceProp prop;
                    ^

    "/tmp/tmpn4ub4z8r/a.cpp", line 10: error: expected a ";"
                    cudaDeviceProp prop;
                                   ^

    "/tmp/tmpn4ub4z8r/a.cpp", line 11: error: identifier "prop" is undefined
                    CHECK_CUDART(cudaGetDeviceProperties(&prop, i));
                    ^

    "/tmp/tmpn4ub4z8r/a.cpp", line 12: error: identifier "prop" is undefined
                    printf("%d%d ", prop.major, prop.minor);
                                    ^

    "/tmp/tmpn4ub4z8r/a.cpp", line 16: warning: last line of file ends without a newline

              ^

    4 errors detected in the compilation of "/tmp/tmpn4ub4z8r/a.cpp".
    **************************************************
    *** WARNING: Cannot check compute capability
    command 'cc' failed with exit status 2
    **************************************************
```

Even trying to help it out by including the compiler and linker flags -- eg:

```bash
LDFLAGS="$CRAY_CUDATOOLKIT_POST_LINK_OPTS" CFLAGS="-I$CUDATOOLKIT_HOME/targets/x86_64-linux/include -noswitcherror" CC=cc CXX=CC pip install cupy
```

doesn't help. I am tempted to refer this to the vendors at this stage -- depending on what @lastephey thinks. In the meantime we've published the (ugly) workaround above.

**Comment by JBlaschke** [comment]
@leofang  For completeness:

> Also, the Perlmutter instruction recommends to install CuPy wheel from PyPI: https://docs.nersc.gov/development/languages/python/using-python-perlmutter/#cupy

I like recommending that users try the wheels first, but it's also important to me that we document how to build python dependencies using the vendor compilers wherever this is feasible. One situation where this might matter is when some python modules need to be compiled with specific vendor compilers, or linked against specific cuda versions. In this situation it is nice to know how all dependencies can be compiled using a single consistent toolchain.

> Maybe opening a ticket with the admin for consultation? 🙂

HA! That would likely land on mine, or @dmargala 's or @lastephey 's desk 😜

**Comment by emcastillo** [comment]
This is a problem of `distutils` where the flags used to compile python are unconditionally set to any UNIX compiler.

https://github.com/pypa/setuptools/blob/main/setuptools/_distutils/sysconfig.py#L219-L221

Also we call this from:
https://github.com/cupy/cupy/blob/master/install/cupy_builder/cupy_setup_build.py#L487-L489

The problem here is that you won't be able to override the CFLAGS passed to the compiler without calling mock or probably creating your own compiler definition for setuptools which I am not sure if it would be able to cleanly skip the sysconfig setting. 

The only immediate way that comes to my mind that can cleanly solve this is to compile Python with nvc. However, I am not sure if that would even work or create other problems for users. But I think it is worth a try.

Thanks for the report! this is an interesting behavior that we were not fully aware. It would be great if we can find a nice fix for this so lets leave this open for discussion.

**Comment by leofang** [comment]
Thanks, @JBlaschke. Emilio is right -- those configs are coming from the build env of the specific Python interpreter in question, and is recorded in `sysconfig` so that when building Python extension modules for this interpreter, the compiler flags can be made consistent. 

Let me add that there is no way out AFAIK -- `sysconfig` is heavily used in the community (CuPy, mpi4py, conda-forge, and almost all open source projects that I am aware of). It's likely that -- if possible at all -- you need to rebuild the Python interpreter for your users using the lowest common denominator flags to make nvc++ happy...
