### ISSUE TITLE
Releasing AArch64 wheels on PyPI

### ISSUE THREAD

**Issue by odidev** [cupy/cupy#6972]
### Description

Hi Team, 

 

The aarch64 wheels for cupy-cuda are released here: https://pip.cupy.dev/aarch64 .This requires installation through ` pip install cupy-cuda11x –f https://pip.cupy.dev/aarch64` and directly installing through `pip install cupy-cuda11x` gives the following error: 
``` 
ERROR: Could not find a version that satisfies the requirement cupy-cuda115 (from versions: none) 
ERROR: No matching distribution found for cupy-cuda115 
``` 

 

May I know if you have any plans for releasing them on PyPI so that the aarch64 wheels can be installed directly through `pip install cupy-cuda11x`?

**Comment by kmaehashi** [comment]
Hi @odidev, thanks for the feedback. For now, we prefer putting it on our pip index rather than PyPI, but it may be worth reconsidering if the amount of aarch64 CUDA users increases. PyPI's storage is a resource shared among the community, so we don't want to occupy the room aggressively.

**Comment by odidev** [comment]
Ok, Thanks.

**Comment by leofang** [comment]
Hi @kmaehashi Is it ok that we revisit this discussion? cuQuantum Python would like to depend on `cupy-wheel` (see [here](https://github.com/NVIDIA/cuQuantum/blob/874adaf19f5d4118e07f7ded99d3e01e492609e7/python/setup.py#L101)) but because we have both x86-64 and aarch64 wheels on PyPI, it means CuPy aarch64 wheels need to be on PyPI too. I believe in the near future RAPIDS will also need it (cc: @sevagh, xref: https://github.com/cupy/cupy/issues/6705).

**Comment by kmaehashi** [comment]
@leofang Will `pip install cuquantum-python -f https://pip.cupy.dev/aarch64` work in that case?

**Comment by leofang** [comment]
It will, but we're a bit hesitant to put this instruction on our documentation. It'd be nicer if this instruction does not lean into downstream 🙂
