### ISSUE TITLE
Support for xp.take?

### ISSUE THREAD

**Issue by arogozhnikov** [cupy/cupy#7425]
### Description

worth adding xp.take from array api standard:
https://data-apis.org/array-api/latest/API_specification/generated/array_api.take.html#array_api.take

I've landed a PR to numpy, I think implementation in cupy is the same?
https://github.com/numpy/numpy/pull/23284/files

**Comment by leofang** [comment]
I believe Alex meant to add `cupy.array_api.take()`. Alex, if you have time to help us it couldn't be better, otherwise, we can take care of it after your NumPy PR is merged. 

This is what we've been doing so far: We usually wait until the PR lands in NumPy ("landing" as in "merged", not just "in progress/in review" 🙂), and then take the patch from the NumPy PR and apply it to CuPy with authorship preserved (in some cases the patches would need convolved editing to fit in CuPy that this process could fail and require manual intervention, especially with regard to device/stream management).

**Comment by arogozhnikov** [comment]
@leofang  PR was merged into numpy, I've created a similar PR here

**Comment by takagi** [comment]
Thanks, @arogozhnikov and @leofang!
