### ISSUE TITLE
current device changed before entering and after leaving `with cupy.cuda.Device(1)` 

### ISSUE THREAD

**Issue by thuzhf** [cupy/cupy#7466]
### Description

If current default device is 1 (torch.cuda.current_device() == 1 or cupy.cuda.runtime.getDevice() == 1), and after you enter `with cupy.cuda.Device(xx)` (whatever xx is, such as 0 or 1 or 2 ...) and **leave** this context, you'll find current device is changed to 0.

### To Reproduce

![image](https://user-images.githubusercontent.com/8064242/225809017-673fc982-e4a4-422a-9fb1-08bca392d733.png)

### Output

<img width="682" alt="image" src="https://user-images.githubusercontent.com/8064242/225809111-1a3f9235-7801-402a-8bd2-55fcd7ce9209.png">

### Installation

Pip (`pip install cupy-cuda113==10.6.0`)

### Additional Information

python version: 3.9.16
CUDA version: 11.3
cupy version: 10.6.0

**Comment by kmaehashi** [comment]
Hi @thuzhf, thanks for the feedback! This confusing behavior will be fixed in the v12 release planned later this month.
https://docs.cupy.dev/en/latest/upgrade.html#change-in-cupy-cuda-device-behavior

CuPy respects the CUDA device set by PyTorch, and vice-versa. You can workaround this issue by making a device switch method consistent (`cupy.cuda.Device` or `torch.cuda.device`) in your codebase.

**Comment by kmaehashi** [comment]
Fixed in CuPy v12 release.
