### ISSUE TITLE
Unexpected memory used by `empty_pinned`

### ISSUE THREAD

**Issue by jemiryguo** [cupy/cupy#7742]
### Description

I found the memory used (indicated by `htop`) is larger than the `empty_pinned` requested. The used memory is always rounded up to the power of 2. e.g. request of 234G will cause 256G useage, request of 14G will cause roughly 16G useage. I read the cupy source code, and found that `empty_pinned` called `alloc_pinned_memory` which only have two lines:
```py
_watcher.check_and_release()
return _current_allocator(size)
```

`_current_allocator` is just the alis for `_malloc`. But `_malloc` don't have this problem!

### To Reproduce

```py
from cupy import cuda
# a = cuda.alloc_pinned_memory(1024 * 1024 * 1024 * 10) # this will occupy 16.7G
a = cuda.pinned_memory._malloc(1024 * 1024 * 1024 * 10) # this will occupy 10.5G
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.31
Python Version               : 3.10.9
CuPy Version                 : 11.5.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.2
SciPy Version                : 1.10.1
Cython Build Version         : 0.29.33
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11020
CUDA Driver Version          : 11080
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : b8d229d
cuDNN Build Version          : 8401
cuDNN Version                : 8600
NCCL Build Version           : 21403
NCCL Runtime Version         : 21501
cuTENSOR Version             : 10602
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100-SXM4-80GB
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:16:00.0
```

**Comment by jemiryguo** [comment]
i donnot think this is the htop problem, because I have total 800G memorys, request 700G memory by `alloc_pinned_memory` will failed but `_malloc` not.

**Comment by kmaehashi** [comment]
> which calls `clp2` to round up to power of 2. @kmaehashi do you recall the reason of doing that (#1372)?

The pinned memory pool uses a very simple dict-based algorithm without chunk split/merge, in contrast to the BFC method used for GPU device memory pool. The dict key has been replaced from `round_512(size)` to `clp2(round_512(size))` to improve the "cache-hit" ratio; otherwise, the pool will be full of unused chunks when a user requests allocations of various size.

Pinned memory (pool) was expected to be used for allocating a buffer for H2D copy to accelerate the memory transfer. At the time the logic was written, we assumed the allocation size to be a few GB at most. Now that H100 has 80-94 GB, it might be a good idea to improve the heuristics, especially for large allocations.

@jemiryguo If you are trying to allocate a large chunk of pinned memory and manage it on your own, you can turn off the pinned memory pool in CuPy.
https://docs.cupy.dev/en/stable/user_guide/memory.html#changing-memory-pool

**Comment by jemiryguo** [comment]
> > which calls `clp2` to round up to power of 2. @kmaehashi do you recall the reason of doing that (#1372)?
> 
> The pinned memory pool uses a very simple dict-based algorithm without chunk split/merge, in contrast to the BFC method used for GPU device memory pool. The dict key has been replaced from `round_512(size)` to `clp2(round_512(size))` to improve the "cache-hit" ratio; otherwise, the pool will be full of unused chunks when a user requests allocations of various size.
> 
> Pinned memory (pool) was expected to be used for allocating a buffer for H2D copy to accelerate the memory transfer. At the time the logic was written, we assumed the allocation size to be a few GB at most. Now that H100 has 80-94 GB, it might be a good idea to improve the heuristics, especially for large allocations.
> 
> @jemiryguo If you are trying to allocate a large chunk of pinned memory and manage it on your own, you can turn off the pinned memory pool in CuPy. https://docs.cupy.dev/en/stable/user_guide/memory.html#changing-memory-pool

Very clear. Thanks a lot.
