### ISSUE TITLE
Some `cupyx.scipy.signal` APIs fall back to NumPy

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#7761]
Some `scipy.signal` APIs depend on `numpy.eigvals`, which computes the eigenvalues of a general matrix. However, cuSolver only provides the eigenvalue solver of a symmetric (Hermitian) matrix but does not the one of a general matrix. Therefore, the `cupyx.scipy.signal` counterparts of such APIs are currently implemented by falling back to `numpy.eigvals` or `numpy.roots`, which calls `numpy.eigvals`.

Such APIs include:
- `cupyx.scipy.signal.findfreqs` #7641
- `cupyx.scipy.signal.tf2zpk` #7652
- `cupyx.scipy.signal.ss2tf` #7652

See:
- https://github.com/cupy/cupy/blob/ae82162be14de46e69b3cd2ab3327fbc94d3eb65/cupyx/scipy/signal/_polyutils.py#L8
- https://github.com/cupy/cupy/blob/ae82162be14de46e69b3cd2ab3327fbc94d3eb65/cupyx/scipy/signal/_polyutils.py#L17

**Comment by emcastillo** [comment]
Lets add a warning in documentation of these routines regarding device synchronization

**Comment by leofang** [comment]
> However, cuSolver only provides the eigenvalue solver of a symmetric (Hermitian) matrix but does not the one of a general matrix. 

Hi @takagi @ev-br @andfoy I could really pick your brains here regarding the general-matrix eigensolver. Why isn't it possible to rewrite the algorithms such that you generate a Hermitian matrix? What's special here? (Context: On the cuSOLVER side, I learned that there's great hesitation in adding the general solver because there's no serious use case. A lot of `eigvals` calls were done, in our opinion, only because people either didn't know `eigvalsh` exists or didn't know their matrix is Hermitian/symmetric. Also, `svd` might help for a lot of use cases (https://github.com/cupy/cupy/issues/6359#issuecomment-1088371230). We would love to know what's missing in this understanding.)

**Comment by takagi** [comment]
Thanks @leofang for letting my head up. As for `numpy.roots`, the roots of a polynomial is found as the eigenvalues of its companion matrix, and the matrix is not symmetric/Hermitian.

https://en.m.wikipedia.org/wiki/Companion_matrix

I suppose we need eigenvalues themselves, not just decomposition, so svd may not work.

However, yes, we might use another algorithm for root finding on GPU that does not use eigenvalues.

https://hal.science/hal-02129742/file/880a5bc7-2a3d-4a66-a539-9755508a949b-author.pdf

I’ll look into other lines that use eigvals...

**Comment by takagi** [comment]
Thanks @leofang for letting my head up. As for `numpy.roots`, the roots of a polynomial is found as the eigenvalues of its companion matrix, and the matrix is not symmetric/Hermitian.

https://en.m.wikipedia.org/wiki/Companion_matrix

I suppose we need eigenvalues themselves, not just decomposition, so svd may not work.

However, yes, we might use another algorithm for root finding on GPU that does not use eigenvalues.

https://hal.science/hal-02129742/file/880a5bc7-2a3d-4a66-a539-9755508a949b-author.pdf

I’ll look into other lines that use eigvals...
