### ISSUE TITLE
Make CuPy run without headers under CUDA 12.2 for Windows

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7776]
Currently, part of CuPy features (which uses `nvcc`) cannot run under CUDA 12.2 for Windows. This is due to the issue in CTK described in #7758.

After this issue has been resolved, `pfn-public-ci/cupy.win.cuda122` CI needs to be reverted as a required status check in [Rules](https://github.com/cupy/cupy/rules) (v12/v13 branch).

**Comment by leofang** [comment]
@kmaehashi My apology, I didn't realize until working on #7851 that long time ago I already [asked the CUB team](https://github.com/NVIDIA/cub/issues/478) for a solution for the error described in https://github.com/cupy/cupy/pull/7758#issuecomment-1652938376, as it appeared in a way I failed to make connection. Long story in short, we hit the error in `cuda_bf16.hpp` (which CuPy does not care at all) because the latest CUB (now part of CCCL) has algorithms specialized for bf16, and we do depend on CUB. The simplest way out is to pass `-DCUB_DISABLE_BF16_SUPPORT` to the compiler (https://github.com/NVIDIA/cub/issues/480), which I started using in #7851. Let's see if it fixes Windows + CUDA 12.2.

**Comment by leofang** [comment]
Now that #7851 is merged, we might consider to revisit the fp16 header update if we have bandwidth.

**Comment by kmaehashi** [comment]
Fixed via #7851 and #7910. Thanks Leo!

**Comment by kmaehashi** [comment]
Recalled that installation guide must be reverted.

https://docs.cupy.dev/en/latest/install.html
> CUDA 12.2 is not yet supported on Windows. See [#7776](https://github.com/cupy/cupy/issues/7776) for details.
