### ISSUE TITLE
CUPY sosfilt_zi some SOS coefficients are not supported2

### ISSUE THREAD

**Issue by LizbethEsther** [cupy/cupy#8028]
### Description

 I asked this question two weeks ago and got an answer, but when I verified the effect of the fix today(I downloaded the corrected file separately for experimentation), I found that the error still exists.         https://github.com/cupy/cupy/pull/7998
from _signaltools import sosfilt_zi,sosfilt
from scipy import signal

low_sos = signal.bessel(1, 0.5, 'lowpass', output='sos', fs=250)
low_sos_cupy = cp.asarray(low_sos)
zi_cupy = sosfilt_zi(low_sos_cupy)
zi_scipy = signal.sosfilt_zi(low_sos)
print(zi_cupy)
print(zi_scipy)
data = creat_sinwav([(37,50)],fs=250,sample_time=10)   #Generate a sine wave function
filtered_cupy, dss_cupy = sosfilt(low_sos_cupy, data, axis=-1, zi=zi_cupy)  #filtered_cupy=inf……nan………………
filtered_scipy,dss_scipy = signal.sosfilt(low_sos,data,axis=-1,zi=zi_scipy)  #value

The inf value also causes my calculations to be Nan and INF， But using scipy calculations gives normal results (without inf and nan)

ps:
def sin_wave(amp=1, f=None, fs=1000, phi=0, t=1000):
    '''
    Generate a sine wave function
    :params amp:   
    :params f:    
    :params fs:  
    :params phi:  
    :params t:    
    '''
    ts = 1 / fs
    n = t / ts
    n = np.arange(n)
    y = amp * np.sin(2 * np.pi * f * n * ts + phi * (np.pi / 180))
    return y

def creat_sinwav(sin_info, fs, sample_time=200):
    datas = np.zeros(int(sample_time * fs))
    for (amp, f) in sin_info:
        datas += sin_wave(amp, f, fs=fs, t=sample_time)
    return datas

### To Reproduce

```py
# Write the code here
```

### Installation

None

### Environment

```
# Paste the output here
```

**Comment by LizbethEsther** [comment]
The inf value also causes my calculations to be wrong，normally there should only be the value

**Comment by takagi** [comment]
I'm looking into both CuPy and SciPy sources to see what is happening here.

**Comment by takagi** [comment]
I can see that a singular matrix is passed here, but don't understand the essential issue.
https://github.com/cupy/cupy/blob/9050fa6e5ce27cd1a280fd208cab5d36eb460e63/cupyx/scipy/signal/_signaltools.py#L1551

@andfoy Do you have some idea regarding the difference between CuPy's sosfilt_zi/lfilter_zi and NumPy's?

**Comment by andfoy** [comment]
The main difference is that SciPy models their state as the sum of the past delays.

That means that for an order two filter you would expect a size 2 ndarray, where its values correspond to `a[1] * x[t - 1] + a[2] * x[t - 2] - b[1] * y[t - 1] - b[2] * y[t - 2]` and `a[2] * x[t - 1] - b[2] * y[t - 1]`.

This makes sense since the SciPy implementation is serial and takes each single value of the signal at the time, computes the sum, carries the result and the delay state to the next value.

CuPy implementation behaves differently since it requires the raw states `[x[t - 2], x[t -  1], y[t - 2], y[t - 1]]`, given the parallel nature of the algorithm chosen, which first applies the "sliding window" for each point, and then propagates the result to the other values.

In order to compute the initial states, the calculations require a little tweak, instead of applying the state-space equations as SciPy does (again due to the serial nature of it's implementation), we use the reduction coefficients defined to do the propagation, which yield the individual states, as opposed of a sum of them.

The docstrings of `lfiltter_zi/sosfilt_zi` state this.

**Comment by andfoy** [comment]
In this case, @LizbethEsther is asking for a FIR filter, whose input delays will be always one for `[x[t - 2], x[t - 1]]` and could be applied using `convolve`.

I haven't taken a look at this particular issue, but a guess is that we could disable IIR computation in `sosfilt` when all of the IIR coefficients are zero. However, it is not clear if applying convolve would be much faster for second order filters whose IIR part is zero.

**Comment by andfoy** [comment]
I can confirm this is an evaluation bug indeed, I'm taking a look at it

**Comment by takagi** [comment]
Does `compute_correction_factors` calculate the reduction coefficients?

**Comment by andfoy** [comment]
Yes, the coefficients are correct. The problem roots in filter coefficients whose values are zero, which lead to all zero columns, and therefore, singular matrices.

The fix here is to omit the equations produced by the zero coefficients. I'm working on this.

An important fact is that the current version works fine when all coefficients are defined.

**Comment by takagi** [comment]
I confirmed that #8034 does fix this issue.
```
filtered_cupy: [ 0.99375596  1.20106779  1.5415863  ...  0.26047838  0.25722551
 -0.10150427]
filtered_scipy: [ 0.99375596  1.20106779  1.5415863  ...  0.26047838  0.25722551
 -0.10150427]
 ```

**Comment by takagi** [comment]
Would you check if the issue is fixed on your side too? @LizbethEsther
