### ISSUE TITLE
Support Cuda Stream creation with Priority

### ISSUE THREAD

**Issue by rajagond** [cupy/cupy#8210]
### Description

Hi,

It appears that CuPy does not support the creation of custom CUDA streams with priority. Since the API for this functionality is already available in CUDA, it would be very helpful if CuPy provided this feature.

Thanks

**Comment by leofang** [comment]
As a workaround, you can access the `cudaStreamCreateWithPriority` API through CUDA Python (need to install it yourself via `pip` or `conda`)
https://nvidia.github.io/cuda-python/module/cudart.html?highlight=cudastreamcreatewithpriority#cuda.cudart.cudaStreamCreateWithPriority
and wrap the returned pointer with `ExternalStream`
https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.ExternalStream.html#cupy.cuda.ExternalStream
so that you can use it as a CuPy stream.

**Comment by leofang** [comment]
Sure, that sounds reasonable. I'd suggest to set `priority=None` as default, meaning we don't care. In terms implementation, you can then fall back to the old API if it's `None`. Do pay attention to the interaction between `priority` and `blocking`.
