### ISSUE TITLE
Lifetime hazards from asynchronous H2D copies

### ISSUE THREAD

**Issue by bmerry** [cupy/cupy#8789]
### Description

The documentation for `cp.array` says

> blocking ([bool](https://docs.python.org/3/library/functions.html#bool)) – Default is False, meaning if a H2D copy is needed it would run asynchronously on the current stream, and users are responsible for ensuring the stream order. For example, writing to the source obj without proper ordering while copying would result in a race condition. If set to True, the copy is synchronous (with respect to the host).

However, this doesn't mention that the function doesn't keep the source obj alive while the asynchronous copy happens. So even if you don't modify the data through `obj`, simply releasing the last reference to `obj` can cause it to be garbage collected, and the memory can then be reallocated from the memory pool (or from a lower level, if not using a pool).

This is mostly a risk when `obj` is backed by pinned memory (which is where I got bitten by this, and spent a few days chasing the race condition). Looking at the source code, when the `obj` is pinned, a temporary transfer buffer is allocated (`_alloc_async_transfer_buffer`) and the data is synchronously copied to that buffer, in which case there is no risk. However, if allocation of the transfer buffer fails, the fallback path directly does an asynchronous copy from the source data, and the risk remains, so this is not purely something people allocating their own pinned memory need to be concerned about.

**Comment by leofang** [comment]
Thanks for reporting. @kmaehashi @asi1024 can correct me, but I think it's not just a documentation issue but a bug that I missed in #7939. Right after `copy_from_host_async` here:
https://github.com/cupy/cupy/blob/118ade4a146d1cc68519f7f661f2c145f0b942c9/cupy/_core/core.pyx#L2588-L2589
we should add `pinned_memory._add_to_watch_list(stream.record(), a_cpu)` to ensure we hold a reference to `obj` as suggested @bmerry. 

A potential concern is that the watcher's `check_and_release` method is not called until next time we allocate pinned memory (through CuPy!), so the reference could be held longer than needed. We might want to consider documenting how to manually release it, similar to `free_all_blocks` for GPU memory.

In the long-term, I would suggest to use the same stream-ordered memory pool for pinned memory too, so that the lifetime management becomes moot. As long as all reads and writes are ordered, it is OK for the object to be destructed while work is still on the fly.

**Comment by bmerry** [comment]
`we should add pinned_memory._add_to_watch_list(stream.record(), a_cpu) to ensure we hold a reference to obj`

Not having to track this myself (as a user) sounds good to me.

> A potential concern is that the watcher's check_and_release method is not called until next time we allocate pinned memory (through CuPy!)

It looks like `_EventWatcher.add` also checks for completed events, so as long as you're continuously doing transfers you shouldn't have unbounded growth. But I agree it's not ideal that code that does a once-off transfer then just computes on the GPU (or possibly uses another library for further transfers) is not going to release the memory.

**Comment by kmaehashi** [comment]
Thanks for reporting this. I agree with the Leo's assessment.

> A potential concern is that the watcher's `check_and_release` method is not called until next time we allocate pinned memory (through CuPy!)

This could be a concern for scenarios where pinned memories are allocated by external libraries, where EventWatcher won't have a chance to clear the reference. I'm interested in how other libraries (like PyTorch) handles this...

**Comment by kmaehashi** [comment]
> This could be a concern for scenarios where pinned memories are allocated by external libraries, where EventWatcher won't have a chance to clear the reference. I'm interested in how other libraries (like PyTorch) handles this...

The relevant parts in PyTorch are:
* https://github.com/pytorch/pytorch/blob/v2.5.1/aten/src/ATen/native/cuda/Copy.cu#L362-L381
* https://github.com/pytorch/pytorch/blob/v2.5.1/aten/src/ATen/cuda/CachingHostAllocator.cpp#L252-L257
* https://github.com/pytorch/pytorch/blob/v2.5.1/aten/src/ATen/core/CachingHostAllocator.h#L182-L210
* https://github.com/pytorch/pytorch/blob/v2.5.1/aten/src/ATen/core/CachingHostAllocator.h#L263-L314

It looks it's almost the same as what CuPy does. The only difference is that PyTorch checks the event both on `allocate` and `empty_cache`, while CuPy only checks the event on `alloc_pinned_memory` and not `free_all_blocks`. Maybe my cross-library situation is too much worrying 😅
