### ISSUE TITLE
Updating docker to cuda9 and cudnn7

### ISSUE THREAD

**Issue by arogozhnikov** [cupy/cupy#935]
Hi, 
cupy and chainer worked well for me with fresh versions of cudnn and cuda for a long time, while other frameworks got this support just recently.
Is there a reason why in dockerfiles you use an older image (namely, nvidia/cuda:7.5-cudnn5-devel)?

I'll be happy to test cupy and chainer for complete compatibility with fresh versions and and send a PR, if you're interested.

**Comment by kmaehashi** [comment]
Thanks for the feedback!
We're keeping the old version, because users running old CUDA driver on Docker host will not be able to run it by updating CUDA version in the image.

Do you usually use Docker for your experiments?
How do you think if CUDA 9 image is available as a separate image, like `chainer/chainer:latest-cuda91`?

**Comment by arogozhnikov** [comment]
Hi @kmaehashi,
yes, I'm typically using docker for my experiments, but that's not wide-spread among my colleagues.

My current pipeline (for the last 2 months) is building a custom image derived from nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04, and installing inside miniconda environment. I took pytorch's Dockerfile as a basis (https://github.com/pytorch/pytorch/blob/master/Dockerfile) and modified it. 
It may worth adding similar Dockerfile to chainer/cupy, but I am not absolutely sure.

So, my current interest is being sure (and demonstrating this to new users) that cupy + chainer supports latest versions of CUDA and Chainer, testing and putting proper versions in dockerfiles is a good initial step.

Your thoughts?

**Comment by kmaehashi** [comment]
Providing Docker images with rich features (e.g., Anaconda/Jupyter/... images with Chainer pre-installed) sounds nice, especially for Chainer. I'll discuss this with the team about this topic.

Currently Chainer/CuPy supports CUDA 7.0, 7.5, 8.0 and 9.0. https://docs-cupy.chainer.org/en/stable/install.html
CUDA 9.1 support  is also coming soon (we observe no issues so far).

Actually we are testing Chainer/CuPy against CUDA versions using internal Jenkins server and [chainer-test](https://github.com/chainer/chainer-test) test tools.  We are also planning to publicize Jenkins server so that everyone can see what variation we are testing with.

**Comment by arogozhnikov** [comment]
> We are also planning to publicize Jenkins server so that everyone can see what variation we are testing with.

That would be great.

**Comment by kmaehashi** [comment]
CuPy v5 now provides CUDA 9.2 / cuDNN v7 docker container.
https://docs-cupy.chainer.org/en/stable/upgrade.html#update-of-docker-images
